// **Generated by mime.py**
#ifndef MIME_GENERATED_C
#define MIME_GENERATED_C
#include <glib-2.0/glib.h>

#include <stdlib.h>

enum mime {
    application_CDFV2=655361,
    application_CDFV2_corrupt=655362,
    application_arj=655363,
    application_base64=655364,
    application_binhex=655365,
    application_book=655366,
    application_clariscad=655367,
    application_commonground=655368,
    application_dicom=655369,
    application_drafting=655370,
    application_epub_zip=655371,
    application_freeloader=655372,
    application_futuresplash=655373,
    application_groupwise=655374,
    application_gzip=655375,
    application_hta=655376,
    application_i_deas=655377,
    application_iges=655378,
    application_inf=655379,
    application_java=655380,
    application_java_archive=655381,
    application_javascript=655382,
    application_json=655383,
    application_marc=655384,
    application_mbedlet=655385,
    application_mime=655386,
    application_mspowerpoint=655387,
    application_msword=655388,
    application_netmc=655389,
    application_octet_stream=655390,
    application_oda=655391,
    application_ogg=655392,
    application_pdf=655393 | 0x40000000,
    application_pgp_signature=655394,
    application_pkcs7_signature=655395,
    application_pkix_cert=655396,
    application_postscript=655397,
    application_pro_eng=655398,
    application_ringing_tones=655399,
    application_smil=655400,
    application_solids=655401,
    application_sounder=655402,
    application_step=655403,
    application_streamingmedia=655404,
    application_vda=655405,
    application_vnd_fdf=655406,
    application_vnd_font_fontforge_sfd=655407,
    application_vnd_hp_hpgl=655408,
    application_vnd_iccprofile=655409,
    application_vnd_ms_cab_compressed=655410,
    application_vnd_ms_excel=655411,
    application_vnd_ms_fontobject=655412,
    application_vnd_ms_opentype=655413 | 0x20000000,
    application_vnd_ms_pki_certstore=655414,
    application_vnd_ms_pki_pko=655415,
    application_vnd_ms_pki_seccat=655416,
    application_vnd_ms_powerpoint=655417,
    application_vnd_ms_project=655418,
    application_vnd_oasis_opendocument_base=655419,
    application_vnd_oasis_opendocument_formula=655420,
    application_vnd_oasis_opendocument_graphics=655421,
    application_vnd_oasis_opendocument_text=655422,
    application_vnd_openxmlformats_officedocument_spreadsheetml_sheet=655423,
    application_vnd_openxmlformats_officedocument_wordprocessingml_document=655424,
    application_vnd_wap_wmlc=655425,
    application_vnd_wap_wmlscriptc=655426,
    application_vnd_xara=655427,
    application_vocaltec_media_desc=655428,
    application_vocaltec_media_file=655429,
    application_winhelp=655430,
    application_wordperfect=655431,
    application_wordperfect6_0=655432,
    application_wordperfect6_1=655433,
    application_x_123=655434,
    application_x_7z_compressed=655435,
    application_x_aim=655436,
    application_x_archive=655437,
    application_x_authorware_bin=655438,
    application_x_authorware_map=655439,
    application_x_authorware_seg=655440,
    application_x_bcpio=655441,
    application_x_bittorrent=655442,
    application_x_bsh=655443,
    application_x_bytecode_python=655444,
    application_x_bzip=655445,
    application_x_bzip2=655446,
    application_x_cbr=655447,
    application_x_cbz=655448 | 0x40000000,
    application_x_cdlink=655449,
    application_x_chat=655450,
    application_x_cocoa=655451,
    application_x_conference=655452,
    application_x_cpio=655453,
    application_x_dbf=655454,
    application_x_dbt=655455,
    application_x_debian_package=655456,
    application_x_deepv=655457,
    application_x_director=655458,
    application_x_dosexec=655459,
    application_x_dvi=655460,
    application_x_elc=655461,
    application_x_empty=1,
    application_x_envoy=655463,
    application_x_esrehber=655464,
    application_x_excel=655465,
    application_x_executable=655466,
    application_x_font_sfn=655467 | 0x20000000,
    application_x_font_ttf=655468 | 0x20000000,
    application_x_freelance=655469,
    application_x_git=655470,
    application_x_gsp=655471,
    application_x_gss=655472,
    application_x_gtar=655473,
    application_x_gzip=655474,
    application_x_hdf=655475,
    application_x_helpfile=655476,
    application_x_httpd_imap=655477,
    application_x_ima=655478,
    application_x_innosetup=655479,
    application_x_internett_signup=655480,
    application_x_inventor=655481,
    application_x_ip2=655482,
    application_x_java_applet=655483,
    application_x_java_commerce=655484,
    application_x_java_image=655485,
    application_x_java_keystore=655486,
    application_x_kdelnk=655487,
    application_x_koan=655488,
    application_x_latex=655489,
    application_x_livescreen=655490,
    application_x_lotus=655491,
    application_x_lzh=655492,
    application_x_lzx=655493,
    application_x_mach_binary=655494,
    application_x_mach_executable=655495,
    application_x_magic_cap_package_1_0=655496,
    application_x_mathcad=655497,
    application_x_meme=655498,
    application_x_midi=655499,
    application_x_mif=655500,
    application_x_mix_transfer=655501,
    application_x_mobipocket_ebook=655502,
    application_x_ms_pdb=655503,
    application_x_ms_reader=655504,
    application_x_navi_animation=655505,
    application_x_navidoc=655506,
    application_x_navimap=655507,
    application_x_navistyle=655508,
    application_x_netcdf=655509,
    application_x_newton_compatible_pkg=655510,
    application_x_object=655511,
    application_x_omc=655512,
    application_x_omcdatamaker=655513,
    application_x_omcregerator=655514,
    application_x_pagemaker=655515,
    application_x_pcl=655516,
    application_x_pixclscript=655517,
    application_x_pkcs7_certreqresp=655518,
    application_x_pkcs7_signature=655519,
    application_x_project=655520,
    application_x_qpro=655521,
    application_x_rar=655522,
    application_x_rpm=655523,
    application_x_sdp=655524,
    application_x_sea=655525,
    application_x_seelogo=655526,
    application_x_setupscript=655527,
    application_x_shar=655528,
    application_x_sharedlib=655529,
    application_x_shockwave_flash=655530,
    application_x_sprite=655531,
    application_x_sqlite3=655532,
    application_x_sv4cpio=655533,
    application_x_sv4crc=655534,
    application_x_tar=655535,
    application_x_tbook=655536,
    application_x_tex_tfm=655537,
    application_x_texinfo=655538,
    application_x_ustar=655539,
    application_x_visio=655540,
    application_x_vnd_audioexplosion_mzz=655541,
    application_x_vnd_ls_xpix=655542,
    application_x_vrml=655543,
    application_x_wais_source=655544,
    application_x_wine_extension_ini=655545,
    application_x_wintalk=655546,
    application_x_world=655547,
    application_x_wri=655548,
    application_x_x509_ca_cert=655549,
    application_x_xz=655550,
    application_xml=655551,
    application_zip=655552,
    audio_it=458945,
    audio_make=458946,
    audio_mid=458947,
    audio_midi=458948,
    audio_mp4=458949,
    audio_mpeg=458950,
    audio_ogg=458951,
    audio_s3m=458952,
    audio_tsp_audio=458953,
    audio_tsplayer=458954,
    audio_vnd_qcelp=458955,
    audio_voxware=458956,
    audio_x_flac=458957,
    audio_x_gsm=458958,
    audio_x_jam=458959,
    audio_x_liveaudio=458960,
    audio_x_m4a=458961,
    audio_x_midi=458962,
    audio_x_mod=458963,
    audio_x_mp4a_latm=458964,
    audio_x_mpeg_3=458965,
    audio_x_mpequrl=458966,
    audio_x_nspaudio=458967,
    audio_x_pn_realaudio=458968,
    audio_x_psid=458969,
    audio_x_realaudio=458970,
    audio_x_twinvq=458971,
    audio_x_twinvq_plugin=458972,
    audio_x_voc=458973,
    audio_x_wav=458974,
    audio_xm=458975,
    font_otf=327904 | 0x20000000,
    font_sfnt=327905 | 0x20000000,
    font_woff=327906 | 0x20000000,
    font_woff2=327907 | 0x20000000,
    image_cmu_raster=524516,
    image_fif=524517,
    image_florian=524518,
    image_g3fax=524519,
    image_gif=524520,
    image_ief=524521,
    image_jpeg=524522,
    image_jutvision=524523,
    image_naplps=524524,
    image_pict=524525,
    image_png=524526,
    image_svg=524527 | 0x80000000,
    image_svg_xml=524528 | 0x80000000,
    image_tiff=524529,
    image_vnd_adobe_photoshop=524530 | 0x80000000,
    image_vnd_djvu=524531 | 0x80000000,
    image_vnd_fpx=524532,
    image_vnd_microsoft_icon=524533,
    image_vnd_rn_realflash=524534,
    image_vnd_rn_realpix=524535,
    image_vnd_wap_wbmp=524536,
    image_vnd_xiff=524537,
    image_webp=524538,
    image_x_cmu_raster=524539,
    image_x_cur=524540,
    image_x_dwg=524541,
    image_x_eps=524542,
    image_x_exr=524543,
    image_x_icns=524544,
    image_x_icon=524545 | 0x80000000,
    image_x_jg=524546,
    image_x_jps=524547,
    image_x_ms_bmp=524548,
    image_x_niff=524549,
    image_x_pcx=524550,
    image_x_pict=524551,
    image_x_portable_bitmap=524552,
    image_x_portable_graymap=524553,
    image_x_portable_pixmap=524554,
    image_x_quicktime=524555,
    image_x_rgb=524556,
    image_x_tga=524557,
    image_x_tiff=524558,
    image_x_xcf=524559 | 0x80000000,
    image_x_xpixmap=524560 | 0x80000000,
    image_x_xwindowdump=524561,
    message_rfc822=196882,
    model_vnd_dwf=65811,
    model_vnd_gdl=65812,
    model_vnd_gs_gdl=65813,
    model_vrml=65814,
    model_x_pov=65815,
    text_asp=590104,
    text_css=590105,
    text_html=590106,
    text_javascript=590107,
    text_mcf=590108,
    text_pascal=590109,
    text_plain=590110,
    text_richtext=590111,
    text_scriplet=590112,
    text_tab_separated_values=590113,
    text_troff=590114,
    text_uri_list=590115,
    text_vnd_abc=590116,
    text_vnd_fmi_flexstor=590117,
    text_vnd_wap_wml=590118,
    text_vnd_wap_wmlscript=590119,
    text_webviewhtml=590120,
    text_x_Algol68=590121,
    text_x_asm=590122,
    text_x_audiosoft_intra=590123,
    text_x_awk=590124,
    text_x_bcpl=590125,
    text_x_c=590126,
    text_x_c__=590127,
    text_x_component=590128,
    text_x_diff=590129,
    text_x_fortran=590130,
    text_x_java=590131,
    text_x_la_asf=590132,
    text_x_lisp=590133,
    text_x_m=590134,
    text_x_m4=590135,
    text_x_makefile=590136,
    text_x_msdos_batch=590137,
    text_x_pascal=590138,
    text_x_perl=590139,
    text_x_php=590140,
    text_x_po=590141,
    text_x_python=590142,
    text_x_ruby=590143,
    text_x_sass=590144,
    text_x_scss=590145,
    text_x_server_parsed_html=590146,
    text_x_setext=590147,
    text_x_sgml=590148,
    text_x_shellscript=590149,
    text_x_speech=590150,
    text_x_tcl=590151,
    text_x_tex=590152,
    text_x_uil=590153,
    text_x_uuencode=590154,
    text_x_vcalendar=590155,
    text_x_vcard=590156,
    text_xml=590157,
    video_animaflex=393550,
    video_avi=393551,
    video_avs_video=393552,
    video_mp4=393553,
    video_mpeg=393554,
    video_quicktime=393555,
    video_vdo=393556,
    video_vivo=393557,
    video_vnd_rn_realvideo=393558,
    video_vosaic=393559,
    video_webm=393560,
    video_x_amt_demorun=393561,
    video_x_amt_showrun=393562,
    video_x_atomic3d_feature=393563,
    video_x_dl=393564,
    video_x_dv=393565,
    video_x_fli=393566,
    video_x_flv=393567,
    video_x_isvideo=393568,
    video_x_jng=393569 | 0x80000000,
    video_x_matroska=393570,
    video_x_mng=393571,
    video_x_motion_jpeg=393572,
    video_x_ms_asf=393573,
    video_x_msvideo=393574,
    video_x_qtc=393575,
    video_x_sgi_movie=393576,
};
char *mime_get_mime_text(unsigned int mime_id) {switch (mime_id) {
case application_arj: return "application/arj";
case application_base64: return "application/base64";
case application_binhex: return "application/binhex";
case application_book: return "application/book";
case application_CDFV2: return "application/CDFV2";
case application_clariscad: return "application/clariscad";
case application_commonground: return "application/commonground";
case application_drafting: return "application/drafting";
case application_freeloader: return "application/freeloader";
case application_futuresplash: return "application/futuresplash";
case application_groupwise: return "application/groupwise";
case application_gzip: return "application/gzip";
case application_hta: return "application/hta";
case application_i_deas: return "application/i-deas";
case application_iges: return "application/iges";
case application_inf: return "application/inf";
case application_java_archive: return "application/java-archive";
case application_java: return "application/java";
case application_javascript: return "application/javascript";
case application_x_archive: return "application/x-archive";
case application_json: return "application/json";
case application_marc: return "application/marc";
case application_mbedlet: return "application/mbedlet";
case application_mime: return "application/mime";
case application_mspowerpoint: return "application/mspowerpoint";
case application_msword: return "application/msword";
case application_netmc: return "application/netmc";
case application_octet_stream: return "application/octet-stream";
case application_oda: return "application/oda";
case application_pdf: return "application/pdf";
case application_pgp_signature: return "application/pgp-signature";
case application_pkcs7_signature: return "application/pkcs7-signature";
case application_pkix_cert: return "application/pkix-cert";
case application_postscript: return "application/postscript";
case application_pro_eng: return "application/pro_eng";
case application_ringing_tones: return "application/ringing-tones";
case application_smil: return "application/smil";
case application_solids: return "application/solids";
case application_sounder: return "application/sounder";
case application_step: return "application/step";
case application_streamingmedia: return "application/streamingmedia";
case application_vda: return "application/vda";
case application_vnd_fdf: return "application/vnd.fdf";
case application_vnd_font_fontforge_sfd: return "application/vnd.font-fontforge-sfd";
case application_vnd_hp_hpgl: return "application/vnd.hp-hpgl";
case application_vnd_ms_excel: return "application/vnd.ms-excel";
case application_vnd_ms_fontobject: return "application/vnd.ms-fontobject";
case application_vnd_ms_opentype: return "application/vnd.ms-opentype";
case application_vnd_ms_pki_certstore: return "application/vnd.ms-pki.certstore";
case application_vnd_ms_pki_pko: return "application/vnd.ms-pki.pko";
case application_vnd_ms_pki_seccat: return "application/vnd.ms-pki.seccat";
case application_vnd_ms_powerpoint: return "application/vnd.ms-powerpoint";
case application_vnd_ms_project: return "application/vnd.ms-project";
case application_vnd_oasis_opendocument_base: return "application/vnd.oasis.opendocument.base";
case application_vnd_oasis_opendocument_formula: return "application/vnd.oasis.opendocument.formula";
case application_vnd_oasis_opendocument_graphics: return "application/vnd.oasis.opendocument.graphics";
case application_vnd_oasis_opendocument_text: return "application/vnd.oasis.opendocument.text";
case application_vnd_wap_wmlc: return "application/vnd.wap.wmlc";
case application_vnd_wap_wmlscriptc: return "application/vnd.wap.wmlscriptc";
case application_vnd_xara: return "application/vnd.xara";
case application_vocaltec_media_desc: return "application/vocaltec-media-desc";
case application_vocaltec_media_file: return "application/vocaltec-media-file";
case application_wordperfect6_0: return "application/wordperfect6.0";
case application_wordperfect6_1: return "application/wordperfect6.1";
case application_wordperfect: return "application/wordperfect";
case application_x_123: return "application/x-123";
case application_x_aim: return "application/x-aim";
case application_x_authorware_bin: return "application/x-authorware-bin";
case application_x_authorware_map: return "application/x-authorware-map";
case application_x_authorware_seg: return "application/x-authorware-seg";
case application_x_bcpio: return "application/x-bcpio";
case application_x_bittorrent: return "application/x-bittorrent";
case application_x_bsh: return "application/x-bsh";
case application_x_bytecode_python: return "application/x-bytecode.python";
case application_x_bzip2: return "application/x-bzip2";
case application_x_bzip: return "application/x-bzip";
case application_x_cdlink: return "application/x-cdlink";
case application_x_chat: return "application/x-chat";
case application_x_cocoa: return "application/x-cocoa";
case application_x_conference: return "application/x-conference";
case application_x_cpio: return "application/x-cpio";
case application_x_dbf: return "application/x-dbf";
case application_x_dbt: return "application/x-dbt";
case application_x_deepv: return "application/x-deepv";
case application_x_director: return "application/x-director";
case application_x_dosexec: return "application/x-dosexec";
case application_x_dvi: return "application/x-dvi";
case application_x_elc: return "application/x-elc";
case application_x_envoy: return "application/x-envoy";
case application_x_esrehber: return "application/x-esrehber";
case application_x_excel: return "application/x-excel";
case application_x_executable: return "application/x-executable";
case application_x_font_sfn: return "application/x-font-sfn";
case application_x_font_ttf: return "application/x-font-ttf";
case application_x_freelance: return "application/x-freelance";
case application_x_git: return "application/x-git";
case application_x_gsp: return "application/x-gsp";
case application_x_gss: return "application/x-gss";
case application_x_gtar: return "application/x-gtar";
case application_x_gzip: return "application/x-gzip";
case application_x_hdf: return "application/x-hdf";
case application_x_helpfile: return "application/x-helpfile";
case application_x_httpd_imap: return "application/x-httpd-imap";
case application_x_ima: return "application/x-ima";
case application_x_internett_signup: return "application/x-internett-signup";
case application_x_inventor: return "application/x-inventor";
case application_x_ip2: return "application/x-ip2";
case application_x_java_applet: return "application/x-java-applet";
case application_x_java_commerce: return "application/x-java-commerce";
case application_x_java_image: return "application/x-java-image";
case application_x_java_keystore: return "application/x-java-keystore";
case application_x_koan: return "application/x-koan";
case application_x_latex: return "application/x-latex";
case application_x_livescreen: return "application/x-livescreen";
case application_x_lotus: return "application/x-lotus";
case application_x_lzh: return "application/x-lzh";
case application_x_lzx: return "application/x-lzx";
case application_x_mach_binary: return "application/x-mach-binary";
case application_x_mach_executable: return "application/x-mach-executable";
case application_x_magic_cap_package_1_0: return "application/x-magic-cap-package-1.0";
case application_x_mathcad: return "application/x-mathcad";
case application_x_meme: return "application/x-meme";
case application_x_midi: return "application/x-midi";
case application_x_mif: return "application/x-mif";
case application_x_mix_transfer: return "application/x-mix-transfer";
case application_xml: return "application/xml";
case application_x_ms_pdb: return "application/x-ms-pdb";
case application_x_navi_animation: return "application/x-navi-animation";
case application_x_navidoc: return "application/x-navidoc";
case application_x_navimap: return "application/x-navimap";
case application_x_navistyle: return "application/x-navistyle";
case application_x_netcdf: return "application/x-netcdf";
case application_x_newton_compatible_pkg: return "application/x-newton-compatible-pkg";
case application_x_object: return "application/x-object";
case application_x_omcdatamaker: return "application/x-omcdatamaker";
case application_x_omc: return "application/x-omc";
case application_x_omcregerator: return "application/x-omcregerator";
case application_x_pagemaker: return "application/x-pagemaker";
case application_x_pcl: return "application/x-pcl";
case application_x_pixclscript: return "application/x-pixclscript";
case application_x_pkcs7_certreqresp: return "application/x-pkcs7-certreqresp";
case application_x_pkcs7_signature: return "application/x-pkcs7-signature";
case application_x_project: return "application/x-project";
case application_x_qpro: return "application/x-qpro";
case application_x_sdp: return "application/x-sdp";
case application_x_sea: return "application/x-sea";
case application_x_seelogo: return "application/x-seelogo";
case application_x_setupscript: return "application/x-setupscript";
case application_x_sharedlib: return "application/x-sharedlib";
case application_x_shar: return "application/x-shar";
case application_x_shockwave_flash: return "application/x-shockwave-flash";
case application_x_sprite: return "application/x-sprite";
case application_x_sqlite3: return "application/x-sqlite3";
case application_x_sv4cpio: return "application/x-sv4cpio";
case application_x_sv4crc: return "application/x-sv4crc";
case application_x_tar: return "application/x-tar";
case application_x_tbook: return "application/x-tbook";
case application_x_texinfo: return "application/x-texinfo";
case application_x_tex_tfm: return "application/x-tex-tfm";
case application_x_ustar: return "application/x-ustar";
case application_x_visio: return "application/x-visio";
case application_x_vnd_audioexplosion_mzz: return "application/x-vnd.audioexplosion.mzz";
case application_x_vnd_ls_xpix: return "application/x-vnd.ls-xpix";
case application_x_vrml: return "application/x-vrml";
case application_x_wais_source: return "application/x-wais-source";
case application_x_wintalk: return "application/x-wintalk";
case application_x_world: return "application/x-world";
case application_x_wri: return "application/x-wri";
case application_x_x509_ca_cert: return "application/x-x509-ca-cert";
case application_x_xz: return "application/x-xz";
case application_zip: return "application/zip";
case audio_it: return "audio/it";
case audio_make: return "audio/make";
case audio_midi: return "audio/midi";
case audio_mid: return "audio/mid";
case audio_mpeg: return "audio/mpeg";
case audio_ogg: return "audio/ogg";
case audio_s3m: return "audio/s3m";
case audio_tsp_audio: return "audio/tsp-audio";
case audio_tsplayer: return "audio/tsplayer";
case audio_vnd_qcelp: return "audio/vnd.qcelp";
case audio_voxware: return "audio/voxware";
case audio_x_gsm: return "audio/x-gsm";
case audio_x_jam: return "audio/x-jam";
case audio_x_liveaudio: return "audio/x-liveaudio";
case audio_x_m4a: return "audio/x-m4a";
case audio_x_midi: return "audio/x-midi";
case audio_x_mod: return "audio/x-mod";
case audio_x_mp4a_latm: return "audio/x-mp4a-latm";
case audio_x_mpeg_3: return "audio/x-mpeg-3";
case audio_x_mpequrl: return "audio/x-mpequrl";
case audio_xm: return "audio/xm";
case audio_x_nspaudio: return "audio/x-nspaudio";
case audio_x_pn_realaudio: return "audio/x-pn-realaudio";
case audio_x_psid: return "audio/x-psid";
case audio_x_realaudio: return "audio/x-realaudio";
case audio_x_twinvq_plugin: return "audio/x-twinvq-plugin";
case audio_x_twinvq: return "audio/x-twinvq";
case audio_x_voc: return "audio/x-voc";
case audio_x_wav: return "audio/x-wav";
case font_otf: return "font/otf";
case font_sfnt: return "font/sfnt";
case image_cmu_raster: return "image/cmu-raster";
case image_fif: return "image/fif";
case image_florian: return "image/florian";
case image_g3fax: return "image/g3fax";
case image_gif: return "image/gif";
case image_ief: return "image/ief";
case image_jpeg: return "image/jpeg";
case image_jutvision: return "image/jutvision";
case image_naplps: return "image/naplps";
case image_pict: return "image/pict";
case image_png: return "image/png";
case image_svg: return "image/svg";
case image_svg_xml: return "image/svg+xml";
case image_vnd_fpx: return "image/vnd.fpx";
case image_vnd_microsoft_icon: return "image/vnd.microsoft.icon";
case image_vnd_rn_realflash: return "image/vnd.rn-realflash";
case image_vnd_rn_realpix: return "image/vnd.rn-realpix";
case image_vnd_wap_wbmp: return "image/vnd.wap.wbmp";
case image_vnd_xiff: return "image/vnd.xiff";
case image_webp: return "image/webp";
case image_x_cmu_raster: return "image/x-cmu-raster";
case image_x_dwg: return "image/x-dwg";
case image_x_eps: return "image/x-eps";
case image_x_icns: return "image/x-icns";
case image_x_icon: return "image/x-icon";
case image_x_jg: return "image/x-jg";
case image_x_jps: return "image/x-jps";
case image_x_ms_bmp: return "image/x-ms-bmp";
case image_x_niff: return "image/x-niff";
case image_x_pcx: return "image/x-pcx";
case image_x_pict: return "image/x-pict";
case image_x_portable_bitmap: return "image/x-portable-bitmap";
case image_x_portable_graymap: return "image/x-portable-graymap";
case image_x_portable_pixmap: return "image/x-portable-pixmap";
case image_x_quicktime: return "image/x-quicktime";
case image_x_rgb: return "image/x-rgb";
case image_x_tiff: return "image/x-tiff";
case image_tiff: return "image/tiff";
case image_x_xcf: return "image/x-xcf";
case image_x_xpixmap: return "image/x-xpixmap";
case message_rfc822: return "message/rfc822";
case model_vnd_dwf: return "model/vnd.dwf";
case model_vrml: return "model/vrml";
case model_x_pov: return "model/x-pov";
case text_asp: return "text/asp";
case text_css: return "text/css";
case text_x_sass: return "text/x-sass";
case text_x_scss: return "text/x-scss";
case text_html: return "text/html";
case text_javascript: return "text/javascript";
case text_mcf: return "text/mcf";
case text_pascal: return "text/pascal";
case text_plain: return "text/plain";
case text_richtext: return "text/richtext";
case text_scriplet: return "text/scriplet";
case text_x_awk: return "text/x-awk";
case video_x_jng: return "video/x-jng";
case video_x_mng: return "video/x-mng";
case image_x_cur: return "image/x-cur";
case image_x_xwindowdump: return "image/x-xwindowdump";
case image_vnd_adobe_photoshop: return "image/vnd.adobe.photoshop";
case text_tab_separated_values: return "text/tab-separated-values";
case text_troff: return "text/troff";
case text_uri_list: return "text/uri-list";
case text_vnd_abc: return "text/vnd.abc";
case text_vnd_fmi_flexstor: return "text/vnd.fmi.flexstor";
case text_vnd_wap_wmlscript: return "text/vnd.wap.wmlscript";
case text_vnd_wap_wml: return "text/vnd.wap.wml";
case text_webviewhtml: return "text/webviewhtml";
case text_x_Algol68: return "text/x-Algol68";
case text_x_asm: return "text/x-asm";
case text_x_audiosoft_intra: return "text/x-audiosoft-intra";
case text_x_bcpl: return "text/x-bcpl";
case text_x_c: return "text/x-c";
case text_x_c__: return "text/x-c++";
case text_x_component: return "text/x-component";
case text_x_diff: return "text/x-diff";
case text_x_fortran: return "text/x-fortran";
case text_x_java: return "text/x-java";
case text_x_la_asf: return "text/x-la-asf";
case text_x_lisp: return "text/x-lisp";
case text_x_m4: return "text/x-m4";
case text_x_makefile: return "text/x-makefile";
case text_xml: return "text/xml";
case text_x_m: return "text/x-m";
case text_x_msdos_batch: return "text/x-msdos-batch";
case text_x_pascal: return "text/x-pascal";
case text_x_perl: return "text/x-perl";
case text_x_php: return "text/x-php";
case text_x_python: return "text/x-python";
case text_x_ruby: return "text/x-ruby";
case text_x_server_parsed_html: return "text/x-server-parsed-html";
case text_x_setext: return "text/x-setext";
case text_x_sgml: return "text/x-sgml";
case text_x_shellscript: return "text/x-shellscript";
case text_x_speech: return "text/x-speech";
case text_x_tex: return "text/x-tex";
case text_x_uil: return "text/x-uil";
case text_x_uuencode: return "text/x-uuencode";
case text_x_vcalendar: return "text/x-vcalendar";
case video_animaflex: return "video/animaflex";
case video_avi: return "video/avi";
case video_avs_video: return "video/avs-video";
case video_mp4: return "video/mp4";
case video_mpeg: return "video/mpeg";
case video_quicktime: return "video/quicktime";
case video_vdo: return "video/vdo";
case video_vivo: return "video/vivo";
case video_vnd_rn_realvideo: return "video/vnd.rn-realvideo";
case video_vosaic: return "video/vosaic";
case video_webm: return "video/webm";
case video_x_amt_demorun: return "video/x-amt-demorun";
case video_x_amt_showrun: return "video/x-amt-showrun";
case video_x_atomic3d_feature: return "video/x-atomic3d-feature";
case video_x_dl: return "video/x-dl";
case video_x_dv: return "video/x-dv";
case video_x_fli: return "video/x-fli";
case video_x_isvideo: return "video/x-isvideo";
case video_x_motion_jpeg: return "video/x-motion-jpeg";
case video_x_ms_asf: return "video/x-ms-asf";
case video_x_qtc: return "video/x-qtc";
case video_x_sgi_movie: return "video/x-sgi-movie";
case application_x_7z_compressed: return "application/x-7z-compressed";
case application_vnd_openxmlformats_officedocument_wordprocessingml_document: return "application/vnd.openxmlformats-officedocument.wordprocessingml.document";
case text_x_po: return "text/x-po";
case application_x_rpm: return "application/x-rpm";
case application_x_debian_package: return "application/x-debian-package";
case application_vnd_iccprofile: return "application/vnd.iccprofile";
case application_dicom: return "application/dicom";
case image_x_exr: return "image/x-exr";
case video_x_matroska: return "video/x-matroska";
case application_x_empty: return "application/x-empty";
case model_vnd_gdl: return "model/vnd.gdl";
case model_vnd_gs_gdl: return "model/vnd.gs.gdl";
case font_woff: return "font/woff";
case font_woff2: return "font/woff2";
case application_epub_zip: return "application/epub+zip";
case application_x_mobipocket_ebook: return "application/x-mobipocket-ebook";
case audio_x_flac: return "audio/x-flac";
case application_x_rar: return "application/x-rar";
case video_x_msvideo: return "video/x-msvideo";
case video_x_flv: return "video/x-flv";
case application_x_kdelnk: return "application/x-kdelnk";
case text_x_tcl: return "text/x-tcl";
case application_ogg: return "application/ogg";
case application_vnd_openxmlformats_officedocument_spreadsheetml_sheet: return "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
case application_vnd_ms_cab_compressed: return "application/vnd.ms-cab-compressed";
case audio_mp4: return "audio/mp4";
case image_vnd_djvu: return "image/vnd.djvu";
case application_x_ms_reader: return "application/x-ms-reader";
case application_CDFV2_corrupt: return "application/CDFV2-corrupt";
case text_x_vcard: return "text/x-vcard";
case application_x_innosetup: return "application/x-innosetup";
case application_winhelp: return "application/winhelp";
case image_x_tga: return "image/x-tga";
case application_x_wine_extension_ini: return "application/x-wine-extension-ini";
case application_x_cbz: return "application/x-cbz";
case application_x_cbr: return "application/x-cbr";
default: return NULL;}}
GHashTable *mime_get_ext_table() {GHashTable *ext_table = g_hash_table_new(g_str_hash, g_str_equal);
g_hash_table_insert(ext_table, "arj", (gpointer)application_arj);
g_hash_table_insert(ext_table, "mme", (gpointer)application_base64);
g_hash_table_insert(ext_table, "hqx", (gpointer)application_binhex);
g_hash_table_insert(ext_table, "boo", (gpointer)application_book);
g_hash_table_insert(ext_table, "book", (gpointer)application_book);
g_hash_table_insert(ext_table, "sdv", (gpointer)application_CDFV2);
g_hash_table_insert(ext_table, "ccad", (gpointer)application_clariscad);
g_hash_table_insert(ext_table, "dp", (gpointer)application_commonground);
g_hash_table_insert(ext_table, "drw", (gpointer)application_drafting);
g_hash_table_insert(ext_table, "frl", (gpointer)application_freeloader);
g_hash_table_insert(ext_table, "spl", (gpointer)application_futuresplash);
g_hash_table_insert(ext_table, "vew", (gpointer)application_groupwise);
g_hash_table_insert(ext_table, "gz", (gpointer)application_gzip);
g_hash_table_insert(ext_table, "hta", (gpointer)application_hta);
g_hash_table_insert(ext_table, "unv", (gpointer)application_i_deas);
g_hash_table_insert(ext_table, "iges", (gpointer)application_iges);
g_hash_table_insert(ext_table, "igs", (gpointer)application_iges);
g_hash_table_insert(ext_table, "inf", (gpointer)application_inf);
g_hash_table_insert(ext_table, "jar", (gpointer)application_java_archive);
g_hash_table_insert(ext_table, "class", (gpointer)application_java);
g_hash_table_insert(ext_table, "a", (gpointer)application_x_archive);
g_hash_table_insert(ext_table, "json", (gpointer)application_json);
g_hash_table_insert(ext_table, "mrc", (gpointer)application_marc);
g_hash_table_insert(ext_table, "mbd", (gpointer)application_mbedlet);
g_hash_table_insert(ext_table, "aps", (gpointer)application_mime);
g_hash_table_insert(ext_table, "ppz", (gpointer)application_mspowerpoint);
g_hash_table_insert(ext_table, "doc", (gpointer)application_msword);
g_hash_table_insert(ext_table, "dot", (gpointer)application_msword);
g_hash_table_insert(ext_table, "w6w", (gpointer)application_msword);
g_hash_table_insert(ext_table, "wiz", (gpointer)application_msword);
g_hash_table_insert(ext_table, "word", (gpointer)application_msword);
g_hash_table_insert(ext_table, "mcp", (gpointer)application_netmc);
g_hash_table_insert(ext_table, "bin", (gpointer)application_octet_stream);
g_hash_table_insert(ext_table, "dump", (gpointer)application_octet_stream);
g_hash_table_insert(ext_table, "gpg", (gpointer)application_octet_stream);
g_hash_table_insert(ext_table, "oda", (gpointer)application_oda);
g_hash_table_insert(ext_table, "pdf", (gpointer)application_pdf);
g_hash_table_insert(ext_table, "pgp", (gpointer)application_pgp_signature);
g_hash_table_insert(ext_table, "p7s", (gpointer)application_pkcs7_signature);
g_hash_table_insert(ext_table, "cer", (gpointer)application_pkix_cert);
g_hash_table_insert(ext_table, "crt", (gpointer)application_pkix_cert);
g_hash_table_insert(ext_table, "ai", (gpointer)application_postscript);
g_hash_table_insert(ext_table, "ps", (gpointer)application_postscript);
g_hash_table_insert(ext_table, "part", (gpointer)application_pro_eng);
g_hash_table_insert(ext_table, "prt", (gpointer)application_pro_eng);
g_hash_table_insert(ext_table, "rng", (gpointer)application_ringing_tones);
g_hash_table_insert(ext_table, "smi", (gpointer)application_smil);
g_hash_table_insert(ext_table, "smil", (gpointer)application_smil);
g_hash_table_insert(ext_table, "sol", (gpointer)application_solids);
g_hash_table_insert(ext_table, "sdr", (gpointer)application_sounder);
g_hash_table_insert(ext_table, "step", (gpointer)application_step);
g_hash_table_insert(ext_table, "stp", (gpointer)application_step);
g_hash_table_insert(ext_table, "ssm", (gpointer)application_streamingmedia);
g_hash_table_insert(ext_table, "vda", (gpointer)application_vda);
g_hash_table_insert(ext_table, "fdf", (gpointer)application_vnd_fdf);
g_hash_table_insert(ext_table, "sfd", (gpointer)application_vnd_font_fontforge_sfd);
g_hash_table_insert(ext_table, "hgl", (gpointer)application_vnd_hp_hpgl);
g_hash_table_insert(ext_table, "hpg", (gpointer)application_vnd_hp_hpgl);
g_hash_table_insert(ext_table, "hpgl", (gpointer)application_vnd_hp_hpgl);
g_hash_table_insert(ext_table, "xlb", (gpointer)application_vnd_ms_excel);
g_hash_table_insert(ext_table, "xlc", (gpointer)application_vnd_ms_excel);
g_hash_table_insert(ext_table, "xll", (gpointer)application_vnd_ms_excel);
g_hash_table_insert(ext_table, "xlm", (gpointer)application_vnd_ms_excel);
g_hash_table_insert(ext_table, "xls", (gpointer)application_vnd_ms_excel);
g_hash_table_insert(ext_table, "xlw", (gpointer)application_vnd_ms_excel);
g_hash_table_insert(ext_table, "eot", (gpointer)application_vnd_ms_fontobject);
g_hash_table_insert(ext_table, "otf", (gpointer)application_vnd_ms_opentype);
g_hash_table_insert(ext_table, "sst", (gpointer)application_vnd_ms_pki_certstore);
g_hash_table_insert(ext_table, "pko", (gpointer)application_vnd_ms_pki_pko);
g_hash_table_insert(ext_table, "cat", (gpointer)application_vnd_ms_pki_seccat);
g_hash_table_insert(ext_table, "pot", (gpointer)application_vnd_ms_powerpoint);
g_hash_table_insert(ext_table, "ppa", (gpointer)application_vnd_ms_powerpoint);
g_hash_table_insert(ext_table, "pps", (gpointer)application_vnd_ms_powerpoint);
g_hash_table_insert(ext_table, "ppt", (gpointer)application_vnd_ms_powerpoint);
g_hash_table_insert(ext_table, "pwz", (gpointer)application_vnd_ms_powerpoint);
g_hash_table_insert(ext_table, "mpp", (gpointer)application_vnd_ms_project);
g_hash_table_insert(ext_table, "odb", (gpointer)application_vnd_oasis_opendocument_base);
g_hash_table_insert(ext_table, "odf", (gpointer)application_vnd_oasis_opendocument_formula);
g_hash_table_insert(ext_table, "odg", (gpointer)application_vnd_oasis_opendocument_graphics);
g_hash_table_insert(ext_table, "odt", (gpointer)application_vnd_oasis_opendocument_text);
g_hash_table_insert(ext_table, "wmlc", (gpointer)application_vnd_wap_wmlc);
g_hash_table_insert(ext_table, "wmlsc", (gpointer)application_vnd_wap_wmlscriptc);
g_hash_table_insert(ext_table, "web", (gpointer)application_vnd_xara);
g_hash_table_insert(ext_table, "vmd", (gpointer)application_vocaltec_media_desc);
g_hash_table_insert(ext_table, "vmf", (gpointer)application_vocaltec_media_file);
g_hash_table_insert(ext_table, "w60", (gpointer)application_wordperfect6_0);
g_hash_table_insert(ext_table, "w61", (gpointer)application_wordperfect6_1);
g_hash_table_insert(ext_table, "wp", (gpointer)application_wordperfect);
g_hash_table_insert(ext_table, "wp5", (gpointer)application_wordperfect);
g_hash_table_insert(ext_table, "wp6", (gpointer)application_wordperfect);
g_hash_table_insert(ext_table, "wpd", (gpointer)application_wordperfect);
g_hash_table_insert(ext_table, "wk1", (gpointer)application_x_123);
g_hash_table_insert(ext_table, "aim", (gpointer)application_x_aim);
g_hash_table_insert(ext_table, "aab", (gpointer)application_x_authorware_bin);
g_hash_table_insert(ext_table, "aam", (gpointer)application_x_authorware_map);
g_hash_table_insert(ext_table, "aas", (gpointer)application_x_authorware_seg);
g_hash_table_insert(ext_table, "bcpio", (gpointer)application_x_bcpio);
g_hash_table_insert(ext_table, "torrent", (gpointer)application_x_bittorrent);
g_hash_table_insert(ext_table, "bsh", (gpointer)application_x_bsh);
g_hash_table_insert(ext_table, "pyc", (gpointer)application_x_bytecode_python);
g_hash_table_insert(ext_table, "boz", (gpointer)application_x_bzip2);
g_hash_table_insert(ext_table, "bz2", (gpointer)application_x_bzip2);
g_hash_table_insert(ext_table, "bz", (gpointer)application_x_bzip);
g_hash_table_insert(ext_table, "vcd", (gpointer)application_x_cdlink);
g_hash_table_insert(ext_table, "cha", (gpointer)application_x_chat);
g_hash_table_insert(ext_table, "chat", (gpointer)application_x_chat);
g_hash_table_insert(ext_table, "cco", (gpointer)application_x_cocoa);
g_hash_table_insert(ext_table, "nsc", (gpointer)application_x_conference);
g_hash_table_insert(ext_table, "cpio", (gpointer)application_x_cpio);
g_hash_table_insert(ext_table, "dbf", (gpointer)application_x_dbf);
g_hash_table_insert(ext_table, "deepv", (gpointer)application_x_deepv);
g_hash_table_insert(ext_table, "dcr", (gpointer)application_x_director);
g_hash_table_insert(ext_table, "dir", (gpointer)application_x_director);
g_hash_table_insert(ext_table, "dxr", (gpointer)application_x_director);
g_hash_table_insert(ext_table, "dll", (gpointer)application_x_dosexec);
g_hash_table_insert(ext_table, "dvi", (gpointer)application_x_dvi);
g_hash_table_insert(ext_table, "elc", (gpointer)application_x_elc);
g_hash_table_insert(ext_table, "env", (gpointer)application_x_envoy);
g_hash_table_insert(ext_table, "evy", (gpointer)application_x_envoy);
g_hash_table_insert(ext_table, "es", (gpointer)application_x_esrehber);
g_hash_table_insert(ext_table, "xla", (gpointer)application_x_excel);
g_hash_table_insert(ext_table, "xld", (gpointer)application_x_excel);
g_hash_table_insert(ext_table, "xlk", (gpointer)application_x_excel);
g_hash_table_insert(ext_table, "xlt", (gpointer)application_x_excel);
g_hash_table_insert(ext_table, "xlv", (gpointer)application_x_excel);
g_hash_table_insert(ext_table, "exe", (gpointer)application_x_executable);
g_hash_table_insert(ext_table, "ttf", (gpointer)application_x_font_ttf);
g_hash_table_insert(ext_table, "pre", (gpointer)application_x_freelance);
g_hash_table_insert(ext_table, "gsp", (gpointer)application_x_gsp);
g_hash_table_insert(ext_table, "gss", (gpointer)application_x_gss);
g_hash_table_insert(ext_table, "gtar", (gpointer)application_x_gtar);
g_hash_table_insert(ext_table, "gzip", (gpointer)application_x_gzip);
g_hash_table_insert(ext_table, "hdf", (gpointer)application_x_hdf);
g_hash_table_insert(ext_table, "help", (gpointer)application_x_helpfile);
g_hash_table_insert(ext_table, "imap", (gpointer)application_x_httpd_imap);
g_hash_table_insert(ext_table, "ima", (gpointer)application_x_ima);
g_hash_table_insert(ext_table, "ins", (gpointer)application_x_internett_signup);
g_hash_table_insert(ext_table, "iv", (gpointer)application_x_inventor);
g_hash_table_insert(ext_table, "ip", (gpointer)application_x_ip2);
g_hash_table_insert(ext_table, "jcm", (gpointer)application_x_java_commerce);
g_hash_table_insert(ext_table, "skd", (gpointer)application_x_koan);
g_hash_table_insert(ext_table, "skm", (gpointer)application_x_koan);
g_hash_table_insert(ext_table, "skp", (gpointer)application_x_koan);
g_hash_table_insert(ext_table, "skt", (gpointer)application_x_koan);
g_hash_table_insert(ext_table, "latex", (gpointer)application_x_latex);
g_hash_table_insert(ext_table, "ltx", (gpointer)application_x_latex);
g_hash_table_insert(ext_table, "ivy", (gpointer)application_x_livescreen);
g_hash_table_insert(ext_table, "wq1", (gpointer)application_x_lotus);
g_hash_table_insert(ext_table, "lzh", (gpointer)application_x_lzh);
g_hash_table_insert(ext_table, "lzx", (gpointer)application_x_lzx);
g_hash_table_insert(ext_table, "jnilib", (gpointer)application_x_mach_binary);
g_hash_table_insert(ext_table, "dylib", (gpointer)application_x_mach_binary);
g_hash_table_insert(ext_table, "mc$", (gpointer)application_x_magic_cap_package_1_0);
g_hash_table_insert(ext_table, "mcd", (gpointer)application_x_mathcad);
g_hash_table_insert(ext_table, "mm", (gpointer)application_x_meme);
g_hash_table_insert(ext_table, "midi", (gpointer)application_x_midi);
g_hash_table_insert(ext_table, "mif", (gpointer)application_x_mif);
g_hash_table_insert(ext_table, "nix", (gpointer)application_x_mix_transfer);
g_hash_table_insert(ext_table, "opf", (gpointer)application_xml);
g_hash_table_insert(ext_table, "pdb", (gpointer)application_x_ms_pdb);
g_hash_table_insert(ext_table, "ani", (gpointer)application_x_navi_animation);
g_hash_table_insert(ext_table, "nvd", (gpointer)application_x_navidoc);
g_hash_table_insert(ext_table, "map", (gpointer)application_x_navimap);
g_hash_table_insert(ext_table, "stl", (gpointer)application_x_navistyle);
g_hash_table_insert(ext_table, "cdf", (gpointer)application_x_netcdf);
g_hash_table_insert(ext_table, "nc", (gpointer)application_x_netcdf);
g_hash_table_insert(ext_table, "pkg", (gpointer)application_x_newton_compatible_pkg);
g_hash_table_insert(ext_table, "o", (gpointer)application_x_object);
g_hash_table_insert(ext_table, "omcd", (gpointer)application_x_omcdatamaker);
g_hash_table_insert(ext_table, "omc", (gpointer)application_x_omc);
g_hash_table_insert(ext_table, "omcr", (gpointer)application_x_omcregerator);
g_hash_table_insert(ext_table, "pm4", (gpointer)application_x_pagemaker);
g_hash_table_insert(ext_table, "pm5", (gpointer)application_x_pagemaker);
g_hash_table_insert(ext_table, "pcl", (gpointer)application_x_pcl);
g_hash_table_insert(ext_table, "plx", (gpointer)application_x_pixclscript);
g_hash_table_insert(ext_table, "p7r", (gpointer)application_x_pkcs7_certreqresp);
g_hash_table_insert(ext_table, "p7a", (gpointer)application_x_pkcs7_signature);
g_hash_table_insert(ext_table, "mpc", (gpointer)application_x_project);
g_hash_table_insert(ext_table, "mpt", (gpointer)application_x_project);
g_hash_table_insert(ext_table, "mpv", (gpointer)application_x_project);
g_hash_table_insert(ext_table, "mpx", (gpointer)application_x_project);
g_hash_table_insert(ext_table, "wb1", (gpointer)application_x_qpro);
g_hash_table_insert(ext_table, "sdp", (gpointer)application_x_sdp);
g_hash_table_insert(ext_table, "sea", (gpointer)application_x_sea);
g_hash_table_insert(ext_table, "sl", (gpointer)application_x_seelogo);
g_hash_table_insert(ext_table, "so", (gpointer)application_x_sharedlib);
g_hash_table_insert(ext_table, "shar", (gpointer)application_x_shar);
g_hash_table_insert(ext_table, "swf", (gpointer)application_x_shockwave_flash);
g_hash_table_insert(ext_table, "spr", (gpointer)application_x_sprite);
g_hash_table_insert(ext_table, "sprite", (gpointer)application_x_sprite);
g_hash_table_insert(ext_table, "sv4cpio", (gpointer)application_x_sv4cpio);
g_hash_table_insert(ext_table, "sv4crc", (gpointer)application_x_sv4crc);
g_hash_table_insert(ext_table, "tar", (gpointer)application_x_tar);
g_hash_table_insert(ext_table, "sbk", (gpointer)application_x_tbook);
g_hash_table_insert(ext_table, "tbk", (gpointer)application_x_tbook);
g_hash_table_insert(ext_table, "texi", (gpointer)application_x_texinfo);
g_hash_table_insert(ext_table, "texinfo", (gpointer)application_x_texinfo);
g_hash_table_insert(ext_table, "tfm", (gpointer)application_x_tex_tfm);
g_hash_table_insert(ext_table, "ustar", (gpointer)application_x_ustar);
g_hash_table_insert(ext_table, "vsd", (gpointer)application_x_visio);
g_hash_table_insert(ext_table, "vst", (gpointer)application_x_visio);
g_hash_table_insert(ext_table, "vsw", (gpointer)application_x_visio);
g_hash_table_insert(ext_table, "mzz", (gpointer)application_x_vnd_audioexplosion_mzz);
g_hash_table_insert(ext_table, "xpix", (gpointer)application_x_vnd_ls_xpix);
g_hash_table_insert(ext_table, "vrml", (gpointer)application_x_vrml);
g_hash_table_insert(ext_table, "src", (gpointer)application_x_wais_source);
g_hash_table_insert(ext_table, "wsrc", (gpointer)application_x_wais_source);
g_hash_table_insert(ext_table, "wtk", (gpointer)application_x_wintalk);
g_hash_table_insert(ext_table, "svr", (gpointer)application_x_world);
g_hash_table_insert(ext_table, "wri", (gpointer)application_x_wri);
g_hash_table_insert(ext_table, "der", (gpointer)application_x_x509_ca_cert);
g_hash_table_insert(ext_table, "xz", (gpointer)application_x_xz);
g_hash_table_insert(ext_table, "zip", (gpointer)application_zip);
g_hash_table_insert(ext_table, "it", (gpointer)audio_it);
g_hash_table_insert(ext_table, "funk", (gpointer)audio_make);
g_hash_table_insert(ext_table, "my", (gpointer)audio_make);
g_hash_table_insert(ext_table, "pfunk", (gpointer)audio_make);
g_hash_table_insert(ext_table, "kar", (gpointer)audio_midi);
g_hash_table_insert(ext_table, "rmi", (gpointer)audio_mid);
g_hash_table_insert(ext_table, "m2a", (gpointer)audio_mpeg);
g_hash_table_insert(ext_table, "mpa", (gpointer)audio_mpeg);
g_hash_table_insert(ext_table, "ogg", (gpointer)audio_ogg);
g_hash_table_insert(ext_table, "s3m", (gpointer)audio_s3m);
g_hash_table_insert(ext_table, "tsi", (gpointer)audio_tsp_audio);
g_hash_table_insert(ext_table, "tsp", (gpointer)audio_tsplayer);
g_hash_table_insert(ext_table, "qcp", (gpointer)audio_vnd_qcelp);
g_hash_table_insert(ext_table, "vox", (gpointer)audio_voxware);
g_hash_table_insert(ext_table, "gsd", (gpointer)audio_x_gsm);
g_hash_table_insert(ext_table, "gsm", (gpointer)audio_x_gsm);
g_hash_table_insert(ext_table, "jam", (gpointer)audio_x_jam);
g_hash_table_insert(ext_table, "lam", (gpointer)audio_x_liveaudio);
g_hash_table_insert(ext_table, "m4a", (gpointer)audio_x_m4a);
g_hash_table_insert(ext_table, "mid", (gpointer)audio_x_midi);
g_hash_table_insert(ext_table, "mp3", (gpointer)audio_x_mpeg_3);
g_hash_table_insert(ext_table, "xm", (gpointer)audio_xm);
g_hash_table_insert(ext_table, "lma", (gpointer)audio_x_nspaudio);
g_hash_table_insert(ext_table, "ram", (gpointer)audio_x_pn_realaudio);
g_hash_table_insert(ext_table, "rm", (gpointer)audio_x_pn_realaudio);
g_hash_table_insert(ext_table, "rmm", (gpointer)audio_x_pn_realaudio);
g_hash_table_insert(ext_table, "rmp", (gpointer)audio_x_pn_realaudio);
g_hash_table_insert(ext_table, "sid", (gpointer)audio_x_psid);
g_hash_table_insert(ext_table, "ra", (gpointer)audio_x_realaudio);
g_hash_table_insert(ext_table, "vqe", (gpointer)audio_x_twinvq_plugin);
g_hash_table_insert(ext_table, "vql", (gpointer)audio_x_twinvq_plugin);
g_hash_table_insert(ext_table, "vqf", (gpointer)audio_x_twinvq);
g_hash_table_insert(ext_table, "voc", (gpointer)audio_x_voc);
g_hash_table_insert(ext_table, "wav", (gpointer)audio_x_wav);
g_hash_table_insert(ext_table, "rast", (gpointer)image_cmu_raster);
g_hash_table_insert(ext_table, "fif", (gpointer)image_fif);
g_hash_table_insert(ext_table, "flo", (gpointer)image_florian);
g_hash_table_insert(ext_table, "turbot", (gpointer)image_florian);
g_hash_table_insert(ext_table, "g3", (gpointer)image_g3fax);
g_hash_table_insert(ext_table, "gif", (gpointer)image_gif);
g_hash_table_insert(ext_table, "ief", (gpointer)image_ief);
g_hash_table_insert(ext_table, "iefs", (gpointer)image_ief);
g_hash_table_insert(ext_table, "jfif", (gpointer)image_jpeg);
g_hash_table_insert(ext_table, "jfif-tbnl", (gpointer)image_jpeg);
g_hash_table_insert(ext_table, "jpe", (gpointer)image_jpeg);
g_hash_table_insert(ext_table, "jpeg", (gpointer)image_jpeg);
g_hash_table_insert(ext_table, "jpg", (gpointer)image_jpeg);
g_hash_table_insert(ext_table, "jut", (gpointer)image_jutvision);
g_hash_table_insert(ext_table, "nap", (gpointer)image_naplps);
g_hash_table_insert(ext_table, "naplps", (gpointer)image_naplps);
g_hash_table_insert(ext_table, "pic", (gpointer)image_pict);
g_hash_table_insert(ext_table, "pict", (gpointer)image_pict);
g_hash_table_insert(ext_table, "png", (gpointer)image_png);
g_hash_table_insert(ext_table, "x-png", (gpointer)image_png);
g_hash_table_insert(ext_table, "svg", (gpointer)image_svg);
g_hash_table_insert(ext_table, "fpx", (gpointer)image_vnd_fpx);
g_hash_table_insert(ext_table, "rf", (gpointer)image_vnd_rn_realflash);
g_hash_table_insert(ext_table, "rp", (gpointer)image_vnd_rn_realpix);
g_hash_table_insert(ext_table, "wbmp", (gpointer)image_vnd_wap_wbmp);
g_hash_table_insert(ext_table, "xif", (gpointer)image_vnd_xiff);
g_hash_table_insert(ext_table, "webp", (gpointer)image_webp);
g_hash_table_insert(ext_table, "ras", (gpointer)image_x_cmu_raster);
g_hash_table_insert(ext_table, "dwg", (gpointer)image_x_dwg);
g_hash_table_insert(ext_table, "dxf", (gpointer)image_x_dwg);
g_hash_table_insert(ext_table, "svf", (gpointer)image_x_dwg);
g_hash_table_insert(ext_table, "ico", (gpointer)image_x_icon);
g_hash_table_insert(ext_table, "art", (gpointer)image_x_jg);
g_hash_table_insert(ext_table, "jps", (gpointer)image_x_jps);
g_hash_table_insert(ext_table, "bm", (gpointer)image_x_ms_bmp);
g_hash_table_insert(ext_table, "bmp", (gpointer)image_x_ms_bmp);
g_hash_table_insert(ext_table, "nif", (gpointer)image_x_niff);
g_hash_table_insert(ext_table, "niff", (gpointer)image_x_niff);
g_hash_table_insert(ext_table, "pcx", (gpointer)image_x_pcx);
g_hash_table_insert(ext_table, "pct", (gpointer)image_x_pict);
g_hash_table_insert(ext_table, "pbm", (gpointer)image_x_portable_bitmap);
g_hash_table_insert(ext_table, "pgm", (gpointer)image_x_portable_graymap);
g_hash_table_insert(ext_table, "ppm", (gpointer)image_x_portable_pixmap);
g_hash_table_insert(ext_table, "qif", (gpointer)image_x_quicktime);
g_hash_table_insert(ext_table, "qti", (gpointer)image_x_quicktime);
g_hash_table_insert(ext_table, "qtif", (gpointer)image_x_quicktime);
g_hash_table_insert(ext_table, "rgb", (gpointer)image_x_rgb);
g_hash_table_insert(ext_table, "tif", (gpointer)image_x_tiff);
g_hash_table_insert(ext_table, "tiff", (gpointer)image_x_tiff);
g_hash_table_insert(ext_table, "xcf", (gpointer)image_x_xcf);
g_hash_table_insert(ext_table, "xpm", (gpointer)image_x_xpixmap);
g_hash_table_insert(ext_table, "mht", (gpointer)message_rfc822);
g_hash_table_insert(ext_table, "mhtml", (gpointer)message_rfc822);
g_hash_table_insert(ext_table, "mime", (gpointer)message_rfc822);
g_hash_table_insert(ext_table, "dwf", (gpointer)model_vnd_dwf);
g_hash_table_insert(ext_table, "wrz", (gpointer)model_vrml);
g_hash_table_insert(ext_table, "pov", (gpointer)model_x_pov);
g_hash_table_insert(ext_table, "asp", (gpointer)text_asp);
g_hash_table_insert(ext_table, "css", (gpointer)text_css);
g_hash_table_insert(ext_table, "sass", (gpointer)text_x_sass);
g_hash_table_insert(ext_table, "scss", (gpointer)text_x_scss);
g_hash_table_insert(ext_table, "acgi", (gpointer)text_html);
g_hash_table_insert(ext_table, "htm", (gpointer)text_html);
g_hash_table_insert(ext_table, "html", (gpointer)text_html);
g_hash_table_insert(ext_table, "htmls", (gpointer)text_html);
g_hash_table_insert(ext_table, "htx", (gpointer)text_html);
g_hash_table_insert(ext_table, "shtml", (gpointer)text_html);
g_hash_table_insert(ext_table, "js", (gpointer)text_javascript);
g_hash_table_insert(ext_table, "mcf", (gpointer)text_mcf);
g_hash_table_insert(ext_table, "pas", (gpointer)text_pascal);
g_hash_table_insert(ext_table, "com", (gpointer)text_plain);
g_hash_table_insert(ext_table, "cmd", (gpointer)text_plain);
g_hash_table_insert(ext_table, "conf", (gpointer)text_plain);
g_hash_table_insert(ext_table, "def", (gpointer)text_plain);
g_hash_table_insert(ext_table, "g", (gpointer)text_plain);
g_hash_table_insert(ext_table, "idc", (gpointer)text_plain);
g_hash_table_insert(ext_table, "list", (gpointer)text_plain);
g_hash_table_insert(ext_table, "lst", (gpointer)text_plain);
g_hash_table_insert(ext_table, "mar", (gpointer)text_plain);
g_hash_table_insert(ext_table, "sdml", (gpointer)text_plain);
g_hash_table_insert(ext_table, "text", (gpointer)text_plain);
g_hash_table_insert(ext_table, "txt", (gpointer)text_plain);
g_hash_table_insert(ext_table, "md", (gpointer)text_plain);
g_hash_table_insert(ext_table, "groovy", (gpointer)text_plain);
g_hash_table_insert(ext_table, "license", (gpointer)text_plain);
g_hash_table_insert(ext_table, "properties", (gpointer)text_plain);
g_hash_table_insert(ext_table, "desktop", (gpointer)text_plain);
g_hash_table_insert(ext_table, "ini", (gpointer)text_plain);
g_hash_table_insert(ext_table, "rst", (gpointer)text_plain);
g_hash_table_insert(ext_table, "cmake", (gpointer)text_plain);
g_hash_table_insert(ext_table, "ipynb", (gpointer)text_plain);
g_hash_table_insert(ext_table, "readme", (gpointer)text_plain);
g_hash_table_insert(ext_table, "less", (gpointer)text_plain);
g_hash_table_insert(ext_table, "lo", (gpointer)text_plain);
g_hash_table_insert(ext_table, "go", (gpointer)text_plain);
g_hash_table_insert(ext_table, "yml", (gpointer)text_plain);
g_hash_table_insert(ext_table, "d", (gpointer)text_plain);
g_hash_table_insert(ext_table, "cs", (gpointer)text_plain);
g_hash_table_insert(ext_table, "hpp", (gpointer)text_plain);
g_hash_table_insert(ext_table, "srt", (gpointer)text_plain);
g_hash_table_insert(ext_table, "rt", (gpointer)text_richtext);
g_hash_table_insert(ext_table, "rtf", (gpointer)text_richtext);
g_hash_table_insert(ext_table, "rtx", (gpointer)text_richtext);
g_hash_table_insert(ext_table, "wsc", (gpointer)text_scriplet);
g_hash_table_insert(ext_table, "awk", (gpointer)text_x_awk);
g_hash_table_insert(ext_table, "jng", (gpointer)video_x_jng);
g_hash_table_insert(ext_table, "mng", (gpointer)video_x_mng);
g_hash_table_insert(ext_table, "tga", (gpointer)image_x_cur);
g_hash_table_insert(ext_table, "xwd", (gpointer)image_x_xwindowdump);
g_hash_table_insert(ext_table, "psd", (gpointer)image_vnd_adobe_photoshop);
g_hash_table_insert(ext_table, "tsv", (gpointer)text_tab_separated_values);
g_hash_table_insert(ext_table, "man", (gpointer)text_troff);
g_hash_table_insert(ext_table, "me", (gpointer)text_troff);
g_hash_table_insert(ext_table, "ms", (gpointer)text_troff);
g_hash_table_insert(ext_table, "roff", (gpointer)text_troff);
g_hash_table_insert(ext_table, "t", (gpointer)text_troff);
g_hash_table_insert(ext_table, "tr", (gpointer)text_troff);
g_hash_table_insert(ext_table, "uni", (gpointer)text_uri_list);
g_hash_table_insert(ext_table, "unis", (gpointer)text_uri_list);
g_hash_table_insert(ext_table, "uri", (gpointer)text_uri_list);
g_hash_table_insert(ext_table, "uris", (gpointer)text_uri_list);
g_hash_table_insert(ext_table, "abc", (gpointer)text_vnd_abc);
g_hash_table_insert(ext_table, "flx", (gpointer)text_vnd_fmi_flexstor);
g_hash_table_insert(ext_table, "wmls", (gpointer)text_vnd_wap_wmlscript);
g_hash_table_insert(ext_table, "wml", (gpointer)text_vnd_wap_wml);
g_hash_table_insert(ext_table, "htt", (gpointer)text_webviewhtml);
g_hash_table_insert(ext_table, "asm", (gpointer)text_x_asm);
g_hash_table_insert(ext_table, "s", (gpointer)text_x_asm);
g_hash_table_insert(ext_table, "aip", (gpointer)text_x_audiosoft_intra);
g_hash_table_insert(ext_table, "c", (gpointer)text_x_c);
g_hash_table_insert(ext_table, "cc", (gpointer)text_x_c);
g_hash_table_insert(ext_table, "h", (gpointer)text_x_c);
g_hash_table_insert(ext_table, "cpp", (gpointer)text_x_c__);
g_hash_table_insert(ext_table, "cxx", (gpointer)text_x_c__);
g_hash_table_insert(ext_table, "c++", (gpointer)text_x_c__);
g_hash_table_insert(ext_table, "htc", (gpointer)text_x_component);
g_hash_table_insert(ext_table, "f", (gpointer)text_x_fortran);
g_hash_table_insert(ext_table, "f77", (gpointer)text_x_fortran);
g_hash_table_insert(ext_table, "f90", (gpointer)text_x_fortran);
g_hash_table_insert(ext_table, "for", (gpointer)text_x_fortran);
g_hash_table_insert(ext_table, "jav", (gpointer)text_x_java);
g_hash_table_insert(ext_table, "java", (gpointer)text_x_java);
g_hash_table_insert(ext_table, "lsx", (gpointer)text_x_la_asf);
g_hash_table_insert(ext_table, "el", (gpointer)text_x_lisp);
g_hash_table_insert(ext_table, "m4", (gpointer)text_x_m4);
g_hash_table_insert(ext_table, "ac", (gpointer)text_x_m4);
g_hash_table_insert(ext_table, "am", (gpointer)text_x_makefile);
g_hash_table_insert(ext_table, "mak", (gpointer)text_x_makefile);
g_hash_table_insert(ext_table, "xml", (gpointer)text_xml);
g_hash_table_insert(ext_table, "pom", (gpointer)text_xml);
g_hash_table_insert(ext_table, "iml", (gpointer)text_xml);
g_hash_table_insert(ext_table, "plist", (gpointer)text_xml);
g_hash_table_insert(ext_table, "m", (gpointer)text_x_m);
g_hash_table_insert(ext_table, "bat", (gpointer)text_x_msdos_batch);
g_hash_table_insert(ext_table, "p", (gpointer)text_x_pascal);
g_hash_table_insert(ext_table, "pl", (gpointer)text_x_perl);
g_hash_table_insert(ext_table, "php", (gpointer)text_x_php);
g_hash_table_insert(ext_table, "py", (gpointer)text_x_python);
g_hash_table_insert(ext_table, "rb", (gpointer)text_x_ruby);
g_hash_table_insert(ext_table, "ssi", (gpointer)text_x_server_parsed_html);
g_hash_table_insert(ext_table, "etx", (gpointer)text_x_setext);
g_hash_table_insert(ext_table, "sgm", (gpointer)text_x_sgml);
g_hash_table_insert(ext_table, "sgml", (gpointer)text_x_sgml);
g_hash_table_insert(ext_table, "sh", (gpointer)text_x_shellscript);
g_hash_table_insert(ext_table, "talk", (gpointer)text_x_speech);
g_hash_table_insert(ext_table, "tex", (gpointer)text_x_tex);
g_hash_table_insert(ext_table, "uil", (gpointer)text_x_uil);
g_hash_table_insert(ext_table, "uue", (gpointer)text_x_uuencode);
g_hash_table_insert(ext_table, "vcs", (gpointer)text_x_vcalendar);
g_hash_table_insert(ext_table, "afl", (gpointer)video_animaflex);
g_hash_table_insert(ext_table, "avi", (gpointer)video_avi);
g_hash_table_insert(ext_table, "avs", (gpointer)video_avs_video);
g_hash_table_insert(ext_table, "mp4", (gpointer)video_mp4);
g_hash_table_insert(ext_table, "m1v", (gpointer)video_mpeg);
g_hash_table_insert(ext_table, "m2v", (gpointer)video_mpeg);
g_hash_table_insert(ext_table, "mpe", (gpointer)video_mpeg);
g_hash_table_insert(ext_table, "mpeg", (gpointer)video_mpeg);
g_hash_table_insert(ext_table, "mpg", (gpointer)video_mpeg);
g_hash_table_insert(ext_table, "moov", (gpointer)video_quicktime);
g_hash_table_insert(ext_table, "mov", (gpointer)video_quicktime);
g_hash_table_insert(ext_table, "qt", (gpointer)video_quicktime);
g_hash_table_insert(ext_table, "vdo", (gpointer)video_vdo);
g_hash_table_insert(ext_table, "viv", (gpointer)video_vivo);
g_hash_table_insert(ext_table, "vivo", (gpointer)video_vivo);
g_hash_table_insert(ext_table, "rv", (gpointer)video_vnd_rn_realvideo);
g_hash_table_insert(ext_table, "vos", (gpointer)video_vosaic);
g_hash_table_insert(ext_table, "webm", (gpointer)video_webm);
g_hash_table_insert(ext_table, "xdr", (gpointer)video_x_amt_demorun);
g_hash_table_insert(ext_table, "xsr", (gpointer)video_x_amt_showrun);
g_hash_table_insert(ext_table, "fmf", (gpointer)video_x_atomic3d_feature);
g_hash_table_insert(ext_table, "dl", (gpointer)video_x_dl);
g_hash_table_insert(ext_table, "dif", (gpointer)video_x_dv);
g_hash_table_insert(ext_table, "dv", (gpointer)video_x_dv);
g_hash_table_insert(ext_table, "fli", (gpointer)video_x_fli);
g_hash_table_insert(ext_table, "isu", (gpointer)video_x_isvideo);
g_hash_table_insert(ext_table, "mjpg", (gpointer)video_x_motion_jpeg);
g_hash_table_insert(ext_table, "asf", (gpointer)video_x_ms_asf);
g_hash_table_insert(ext_table, "asx", (gpointer)video_x_ms_asf);
g_hash_table_insert(ext_table, "qtc", (gpointer)video_x_qtc);
g_hash_table_insert(ext_table, "movie", (gpointer)video_x_sgi_movie);
g_hash_table_insert(ext_table, "mv", (gpointer)video_x_sgi_movie);
g_hash_table_insert(ext_table, "7z", (gpointer)application_x_7z_compressed);
g_hash_table_insert(ext_table, "docx", (gpointer)application_vnd_openxmlformats_officedocument_wordprocessingml_document);
g_hash_table_insert(ext_table, "po", (gpointer)text_x_po);
g_hash_table_insert(ext_table, "rpm", (gpointer)application_x_rpm);
g_hash_table_insert(ext_table, "deb", (gpointer)application_x_debian_package);
g_hash_table_insert(ext_table, "icm", (gpointer)application_vnd_iccprofile);
g_hash_table_insert(ext_table, "dcm", (gpointer)application_dicom);
g_hash_table_insert(ext_table, "exr", (gpointer)image_x_exr);
g_hash_table_insert(ext_table, "mkv", (gpointer)video_x_matroska);
g_hash_table_insert(ext_table, "gdl", (gpointer)model_vnd_gdl);
g_hash_table_insert(ext_table, "gdsl", (gpointer)model_vnd_gs_gdl);
g_hash_table_insert(ext_table, "woff", (gpointer)font_woff);
g_hash_table_insert(ext_table, "woff2", (gpointer)font_woff2);
g_hash_table_insert(ext_table, "epub", (gpointer)application_epub_zip);
g_hash_table_insert(ext_table, "mobi", (gpointer)application_x_mobipocket_ebook);
g_hash_table_insert(ext_table, "flac", (gpointer)audio_x_flac);
g_hash_table_insert(ext_table, "rar", (gpointer)application_x_rar);
g_hash_table_insert(ext_table, "divx", (gpointer)video_x_msvideo);
g_hash_table_insert(ext_table, "flv", (gpointer)video_x_flv);
g_hash_table_insert(ext_table, "ogv", (gpointer)application_ogg);
g_hash_table_insert(ext_table, "xlsx", (gpointer)application_vnd_openxmlformats_officedocument_spreadsheetml_sheet);
g_hash_table_insert(ext_table, "cab", (gpointer)application_vnd_ms_cab_compressed);
g_hash_table_insert(ext_table, "m4b", (gpointer)audio_mp4);
g_hash_table_insert(ext_table, "djvu", (gpointer)image_vnd_djvu);
g_hash_table_insert(ext_table, "lit", (gpointer)application_x_ms_reader);
g_hash_table_insert(ext_table, "vcf", (gpointer)text_x_vcard);
g_hash_table_insert(ext_table, "hlp", (gpointer)application_winhelp);
g_hash_table_insert(ext_table, "cbz", (gpointer)application_x_cbz);
g_hash_table_insert(ext_table, "cbr", (gpointer)application_x_cbr);
return ext_table;}
GHashTable *mime_get_mime_table() {GHashTable *mime_table = g_hash_table_new(g_str_hash, g_str_equal);
g_hash_table_insert(mime_table, "application/arj", (gpointer)application_arj);
g_hash_table_insert(mime_table, "application/base64", (gpointer)application_base64);
g_hash_table_insert(mime_table, "application/binhex", (gpointer)application_binhex);
g_hash_table_insert(mime_table, "application/book", (gpointer)application_book);
g_hash_table_insert(mime_table, "application/CDFV2", (gpointer)application_CDFV2);
g_hash_table_insert(mime_table, "application/clariscad", (gpointer)application_clariscad);
g_hash_table_insert(mime_table, "application/commonground", (gpointer)application_commonground);
g_hash_table_insert(mime_table, "application/drafting", (gpointer)application_drafting);
g_hash_table_insert(mime_table, "application/freeloader", (gpointer)application_freeloader);
g_hash_table_insert(mime_table, "application/futuresplash", (gpointer)application_futuresplash);
g_hash_table_insert(mime_table, "application/groupwise", (gpointer)application_groupwise);
g_hash_table_insert(mime_table, "application/gzip", (gpointer)application_gzip);
g_hash_table_insert(mime_table, "application/hta", (gpointer)application_hta);
g_hash_table_insert(mime_table, "application/i-deas", (gpointer)application_i_deas);
g_hash_table_insert(mime_table, "application/iges", (gpointer)application_iges);
g_hash_table_insert(mime_table, "application/inf", (gpointer)application_inf);
g_hash_table_insert(mime_table, "application/java-archive", (gpointer)application_java_archive);
g_hash_table_insert(mime_table, "application/java", (gpointer)application_java);
g_hash_table_insert(mime_table, "application/javascript", (gpointer)application_javascript);
g_hash_table_insert(mime_table, "application/x-archive", (gpointer)application_x_archive);
g_hash_table_insert(mime_table, "application/json", (gpointer)application_json);
g_hash_table_insert(mime_table, "application/marc", (gpointer)application_marc);
g_hash_table_insert(mime_table, "application/mbedlet", (gpointer)application_mbedlet);
g_hash_table_insert(mime_table, "application/mime", (gpointer)application_mime);
g_hash_table_insert(mime_table, "application/mspowerpoint", (gpointer)application_mspowerpoint);
g_hash_table_insert(mime_table, "application/msword", (gpointer)application_msword);
g_hash_table_insert(mime_table, "application/netmc", (gpointer)application_netmc);
g_hash_table_insert(mime_table, "application/octet-stream", (gpointer)application_octet_stream);
g_hash_table_insert(mime_table, "application/oda", (gpointer)application_oda);
g_hash_table_insert(mime_table, "application/pdf", (gpointer)application_pdf);
g_hash_table_insert(mime_table, "application/pgp-signature", (gpointer)application_pgp_signature);
g_hash_table_insert(mime_table, "application/pkcs7-signature", (gpointer)application_pkcs7_signature);
g_hash_table_insert(mime_table, "application/pkix-cert", (gpointer)application_pkix_cert);
g_hash_table_insert(mime_table, "application/postscript", (gpointer)application_postscript);
g_hash_table_insert(mime_table, "application/pro_eng", (gpointer)application_pro_eng);
g_hash_table_insert(mime_table, "application/ringing-tones", (gpointer)application_ringing_tones);
g_hash_table_insert(mime_table, "application/smil", (gpointer)application_smil);
g_hash_table_insert(mime_table, "application/solids", (gpointer)application_solids);
g_hash_table_insert(mime_table, "application/sounder", (gpointer)application_sounder);
g_hash_table_insert(mime_table, "application/step", (gpointer)application_step);
g_hash_table_insert(mime_table, "application/streamingmedia", (gpointer)application_streamingmedia);
g_hash_table_insert(mime_table, "application/vda", (gpointer)application_vda);
g_hash_table_insert(mime_table, "application/vnd.fdf", (gpointer)application_vnd_fdf);
g_hash_table_insert(mime_table, "application/vnd.font-fontforge-sfd", (gpointer)application_vnd_font_fontforge_sfd);
g_hash_table_insert(mime_table, "application/vnd.hp-hpgl", (gpointer)application_vnd_hp_hpgl);
g_hash_table_insert(mime_table, "application/vnd.ms-excel", (gpointer)application_vnd_ms_excel);
g_hash_table_insert(mime_table, "application/vnd.ms-fontobject", (gpointer)application_vnd_ms_fontobject);
g_hash_table_insert(mime_table, "application/vnd.ms-opentype", (gpointer)application_vnd_ms_opentype);
g_hash_table_insert(mime_table, "application/vnd.ms-pki.certstore", (gpointer)application_vnd_ms_pki_certstore);
g_hash_table_insert(mime_table, "application/vnd.ms-pki.pko", (gpointer)application_vnd_ms_pki_pko);
g_hash_table_insert(mime_table, "application/vnd.ms-pki.seccat", (gpointer)application_vnd_ms_pki_seccat);
g_hash_table_insert(mime_table, "application/vnd.ms-powerpoint", (gpointer)application_vnd_ms_powerpoint);
g_hash_table_insert(mime_table, "application/vnd.ms-project", (gpointer)application_vnd_ms_project);
g_hash_table_insert(mime_table, "application/vnd.oasis.opendocument.base", (gpointer)application_vnd_oasis_opendocument_base);
g_hash_table_insert(mime_table, "application/vnd.oasis.opendocument.formula", (gpointer)application_vnd_oasis_opendocument_formula);
g_hash_table_insert(mime_table, "application/vnd.oasis.opendocument.graphics", (gpointer)application_vnd_oasis_opendocument_graphics);
g_hash_table_insert(mime_table, "application/vnd.oasis.opendocument.text", (gpointer)application_vnd_oasis_opendocument_text);
g_hash_table_insert(mime_table, "application/vnd.wap.wmlc", (gpointer)application_vnd_wap_wmlc);
g_hash_table_insert(mime_table, "application/vnd.wap.wmlscriptc", (gpointer)application_vnd_wap_wmlscriptc);
g_hash_table_insert(mime_table, "application/vnd.xara", (gpointer)application_vnd_xara);
g_hash_table_insert(mime_table, "application/vocaltec-media-desc", (gpointer)application_vocaltec_media_desc);
g_hash_table_insert(mime_table, "application/vocaltec-media-file", (gpointer)application_vocaltec_media_file);
g_hash_table_insert(mime_table, "application/wordperfect6.0", (gpointer)application_wordperfect6_0);
g_hash_table_insert(mime_table, "application/wordperfect6.1", (gpointer)application_wordperfect6_1);
g_hash_table_insert(mime_table, "application/wordperfect", (gpointer)application_wordperfect);
g_hash_table_insert(mime_table, "application/x-123", (gpointer)application_x_123);
g_hash_table_insert(mime_table, "application/x-aim", (gpointer)application_x_aim);
g_hash_table_insert(mime_table, "application/x-authorware-bin", (gpointer)application_x_authorware_bin);
g_hash_table_insert(mime_table, "application/x-authorware-map", (gpointer)application_x_authorware_map);
g_hash_table_insert(mime_table, "application/x-authorware-seg", (gpointer)application_x_authorware_seg);
g_hash_table_insert(mime_table, "application/x-bcpio", (gpointer)application_x_bcpio);
g_hash_table_insert(mime_table, "application/x-bittorrent", (gpointer)application_x_bittorrent);
g_hash_table_insert(mime_table, "application/x-bsh", (gpointer)application_x_bsh);
g_hash_table_insert(mime_table, "application/x-bytecode.python", (gpointer)application_x_bytecode_python);
g_hash_table_insert(mime_table, "application/x-bzip2", (gpointer)application_x_bzip2);
g_hash_table_insert(mime_table, "application/x-bzip", (gpointer)application_x_bzip);
g_hash_table_insert(mime_table, "application/x-cdlink", (gpointer)application_x_cdlink);
g_hash_table_insert(mime_table, "application/x-chat", (gpointer)application_x_chat);
g_hash_table_insert(mime_table, "application/x-cocoa", (gpointer)application_x_cocoa);
g_hash_table_insert(mime_table, "application/x-conference", (gpointer)application_x_conference);
g_hash_table_insert(mime_table, "application/x-cpio", (gpointer)application_x_cpio);
g_hash_table_insert(mime_table, "application/x-dbf", (gpointer)application_x_dbf);
g_hash_table_insert(mime_table, "application/x-dbt", (gpointer)application_x_dbt);
g_hash_table_insert(mime_table, "application/x-deepv", (gpointer)application_x_deepv);
g_hash_table_insert(mime_table, "application/x-director", (gpointer)application_x_director);
g_hash_table_insert(mime_table, "application/x-dosexec", (gpointer)application_x_dosexec);
g_hash_table_insert(mime_table, "application/x-dvi", (gpointer)application_x_dvi);
g_hash_table_insert(mime_table, "application/x-elc", (gpointer)application_x_elc);
g_hash_table_insert(mime_table, "application/x-envoy", (gpointer)application_x_envoy);
g_hash_table_insert(mime_table, "application/x-esrehber", (gpointer)application_x_esrehber);
g_hash_table_insert(mime_table, "application/x-excel", (gpointer)application_x_excel);
g_hash_table_insert(mime_table, "application/x-executable", (gpointer)application_x_executable);
g_hash_table_insert(mime_table, "application/x-font-sfn", (gpointer)application_x_font_sfn);
g_hash_table_insert(mime_table, "application/x-font-ttf", (gpointer)application_x_font_ttf);
g_hash_table_insert(mime_table, "application/x-freelance", (gpointer)application_x_freelance);
g_hash_table_insert(mime_table, "application/x-git", (gpointer)application_x_git);
g_hash_table_insert(mime_table, "application/x-gsp", (gpointer)application_x_gsp);
g_hash_table_insert(mime_table, "application/x-gss", (gpointer)application_x_gss);
g_hash_table_insert(mime_table, "application/x-gtar", (gpointer)application_x_gtar);
g_hash_table_insert(mime_table, "application/x-gzip", (gpointer)application_x_gzip);
g_hash_table_insert(mime_table, "application/x-hdf", (gpointer)application_x_hdf);
g_hash_table_insert(mime_table, "application/x-helpfile", (gpointer)application_x_helpfile);
g_hash_table_insert(mime_table, "application/x-httpd-imap", (gpointer)application_x_httpd_imap);
g_hash_table_insert(mime_table, "application/x-ima", (gpointer)application_x_ima);
g_hash_table_insert(mime_table, "application/x-internett-signup", (gpointer)application_x_internett_signup);
g_hash_table_insert(mime_table, "application/x-inventor", (gpointer)application_x_inventor);
g_hash_table_insert(mime_table, "application/x-ip2", (gpointer)application_x_ip2);
g_hash_table_insert(mime_table, "application/x-java-applet", (gpointer)application_x_java_applet);
g_hash_table_insert(mime_table, "application/x-java-commerce", (gpointer)application_x_java_commerce);
g_hash_table_insert(mime_table, "application/x-java-image", (gpointer)application_x_java_image);
g_hash_table_insert(mime_table, "application/x-java-keystore", (gpointer)application_x_java_keystore);
g_hash_table_insert(mime_table, "application/x-koan", (gpointer)application_x_koan);
g_hash_table_insert(mime_table, "application/x-latex", (gpointer)application_x_latex);
g_hash_table_insert(mime_table, "application/x-livescreen", (gpointer)application_x_livescreen);
g_hash_table_insert(mime_table, "application/x-lotus", (gpointer)application_x_lotus);
g_hash_table_insert(mime_table, "application/x-lzh", (gpointer)application_x_lzh);
g_hash_table_insert(mime_table, "application/x-lzx", (gpointer)application_x_lzx);
g_hash_table_insert(mime_table, "application/x-mach-binary", (gpointer)application_x_mach_binary);
g_hash_table_insert(mime_table, "application/x-mach-executable", (gpointer)application_x_mach_executable);
g_hash_table_insert(mime_table, "application/x-magic-cap-package-1.0", (gpointer)application_x_magic_cap_package_1_0);
g_hash_table_insert(mime_table, "application/x-mathcad", (gpointer)application_x_mathcad);
g_hash_table_insert(mime_table, "application/x-meme", (gpointer)application_x_meme);
g_hash_table_insert(mime_table, "application/x-midi", (gpointer)application_x_midi);
g_hash_table_insert(mime_table, "application/x-mif", (gpointer)application_x_mif);
g_hash_table_insert(mime_table, "application/x-mix-transfer", (gpointer)application_x_mix_transfer);
g_hash_table_insert(mime_table, "application/xml", (gpointer)application_xml);
g_hash_table_insert(mime_table, "application/x-ms-pdb", (gpointer)application_x_ms_pdb);
g_hash_table_insert(mime_table, "application/x-navi-animation", (gpointer)application_x_navi_animation);
g_hash_table_insert(mime_table, "application/x-navidoc", (gpointer)application_x_navidoc);
g_hash_table_insert(mime_table, "application/x-navimap", (gpointer)application_x_navimap);
g_hash_table_insert(mime_table, "application/x-navistyle", (gpointer)application_x_navistyle);
g_hash_table_insert(mime_table, "application/x-netcdf", (gpointer)application_x_netcdf);
g_hash_table_insert(mime_table, "application/x-newton-compatible-pkg", (gpointer)application_x_newton_compatible_pkg);
g_hash_table_insert(mime_table, "application/x-object", (gpointer)application_x_object);
g_hash_table_insert(mime_table, "application/x-omcdatamaker", (gpointer)application_x_omcdatamaker);
g_hash_table_insert(mime_table, "application/x-omc", (gpointer)application_x_omc);
g_hash_table_insert(mime_table, "application/x-omcregerator", (gpointer)application_x_omcregerator);
g_hash_table_insert(mime_table, "application/x-pagemaker", (gpointer)application_x_pagemaker);
g_hash_table_insert(mime_table, "application/x-pcl", (gpointer)application_x_pcl);
g_hash_table_insert(mime_table, "application/x-pixclscript", (gpointer)application_x_pixclscript);
g_hash_table_insert(mime_table, "application/x-pkcs7-certreqresp", (gpointer)application_x_pkcs7_certreqresp);
g_hash_table_insert(mime_table, "application/x-pkcs7-signature", (gpointer)application_x_pkcs7_signature);
g_hash_table_insert(mime_table, "application/x-project", (gpointer)application_x_project);
g_hash_table_insert(mime_table, "application/x-qpro", (gpointer)application_x_qpro);
g_hash_table_insert(mime_table, "application/x-sdp", (gpointer)application_x_sdp);
g_hash_table_insert(mime_table, "application/x-sea", (gpointer)application_x_sea);
g_hash_table_insert(mime_table, "application/x-seelogo", (gpointer)application_x_seelogo);
g_hash_table_insert(mime_table, "application/x-setupscript", (gpointer)application_x_setupscript);
g_hash_table_insert(mime_table, "application/x-sharedlib", (gpointer)application_x_sharedlib);
g_hash_table_insert(mime_table, "application/x-shar", (gpointer)application_x_shar);
g_hash_table_insert(mime_table, "application/x-shockwave-flash", (gpointer)application_x_shockwave_flash);
g_hash_table_insert(mime_table, "application/x-sprite", (gpointer)application_x_sprite);
g_hash_table_insert(mime_table, "application/x-sqlite3", (gpointer)application_x_sqlite3);
g_hash_table_insert(mime_table, "application/x-sv4cpio", (gpointer)application_x_sv4cpio);
g_hash_table_insert(mime_table, "application/x-sv4crc", (gpointer)application_x_sv4crc);
g_hash_table_insert(mime_table, "application/x-tar", (gpointer)application_x_tar);
g_hash_table_insert(mime_table, "application/x-tbook", (gpointer)application_x_tbook);
g_hash_table_insert(mime_table, "application/x-texinfo", (gpointer)application_x_texinfo);
g_hash_table_insert(mime_table, "application/x-tex-tfm", (gpointer)application_x_tex_tfm);
g_hash_table_insert(mime_table, "application/x-ustar", (gpointer)application_x_ustar);
g_hash_table_insert(mime_table, "application/x-visio", (gpointer)application_x_visio);
g_hash_table_insert(mime_table, "application/x-vnd.audioexplosion.mzz", (gpointer)application_x_vnd_audioexplosion_mzz);
g_hash_table_insert(mime_table, "application/x-vnd.ls-xpix", (gpointer)application_x_vnd_ls_xpix);
g_hash_table_insert(mime_table, "application/x-vrml", (gpointer)application_x_vrml);
g_hash_table_insert(mime_table, "application/x-wais-source", (gpointer)application_x_wais_source);
g_hash_table_insert(mime_table, "application/x-wintalk", (gpointer)application_x_wintalk);
g_hash_table_insert(mime_table, "application/x-world", (gpointer)application_x_world);
g_hash_table_insert(mime_table, "application/x-wri", (gpointer)application_x_wri);
g_hash_table_insert(mime_table, "application/x-x509-ca-cert", (gpointer)application_x_x509_ca_cert);
g_hash_table_insert(mime_table, "application/x-xz", (gpointer)application_x_xz);
g_hash_table_insert(mime_table, "application/zip", (gpointer)application_zip);
g_hash_table_insert(mime_table, "audio/it", (gpointer)audio_it);
g_hash_table_insert(mime_table, "audio/make", (gpointer)audio_make);
g_hash_table_insert(mime_table, "audio/midi", (gpointer)audio_midi);
g_hash_table_insert(mime_table, "audio/mid", (gpointer)audio_mid);
g_hash_table_insert(mime_table, "audio/mpeg", (gpointer)audio_mpeg);
g_hash_table_insert(mime_table, "audio/ogg", (gpointer)audio_ogg);
g_hash_table_insert(mime_table, "audio/s3m", (gpointer)audio_s3m);
g_hash_table_insert(mime_table, "audio/tsp-audio", (gpointer)audio_tsp_audio);
g_hash_table_insert(mime_table, "audio/tsplayer", (gpointer)audio_tsplayer);
g_hash_table_insert(mime_table, "audio/vnd.qcelp", (gpointer)audio_vnd_qcelp);
g_hash_table_insert(mime_table, "audio/voxware", (gpointer)audio_voxware);
g_hash_table_insert(mime_table, "audio/x-gsm", (gpointer)audio_x_gsm);
g_hash_table_insert(mime_table, "audio/x-jam", (gpointer)audio_x_jam);
g_hash_table_insert(mime_table, "audio/x-liveaudio", (gpointer)audio_x_liveaudio);
g_hash_table_insert(mime_table, "audio/x-m4a", (gpointer)audio_x_m4a);
g_hash_table_insert(mime_table, "audio/x-midi", (gpointer)audio_x_midi);
g_hash_table_insert(mime_table, "audio/x-mod", (gpointer)audio_x_mod);
g_hash_table_insert(mime_table, "audio/x-mp4a-latm", (gpointer)audio_x_mp4a_latm);
g_hash_table_insert(mime_table, "audio/x-mpeg-3", (gpointer)audio_x_mpeg_3);
g_hash_table_insert(mime_table, "audio/x-mpequrl", (gpointer)audio_x_mpequrl);
g_hash_table_insert(mime_table, "audio/xm", (gpointer)audio_xm);
g_hash_table_insert(mime_table, "audio/x-nspaudio", (gpointer)audio_x_nspaudio);
g_hash_table_insert(mime_table, "audio/x-pn-realaudio", (gpointer)audio_x_pn_realaudio);
g_hash_table_insert(mime_table, "audio/x-psid", (gpointer)audio_x_psid);
g_hash_table_insert(mime_table, "audio/x-realaudio", (gpointer)audio_x_realaudio);
g_hash_table_insert(mime_table, "audio/x-twinvq-plugin", (gpointer)audio_x_twinvq_plugin);
g_hash_table_insert(mime_table, "audio/x-twinvq", (gpointer)audio_x_twinvq);
g_hash_table_insert(mime_table, "audio/x-voc", (gpointer)audio_x_voc);
g_hash_table_insert(mime_table, "audio/x-wav", (gpointer)audio_x_wav);
g_hash_table_insert(mime_table, "font/otf", (gpointer)font_otf);
g_hash_table_insert(mime_table, "font/sfnt", (gpointer)font_sfnt);
g_hash_table_insert(mime_table, "image/cmu-raster", (gpointer)image_cmu_raster);
g_hash_table_insert(mime_table, "image/fif", (gpointer)image_fif);
g_hash_table_insert(mime_table, "image/florian", (gpointer)image_florian);
g_hash_table_insert(mime_table, "image/g3fax", (gpointer)image_g3fax);
g_hash_table_insert(mime_table, "image/gif", (gpointer)image_gif);
g_hash_table_insert(mime_table, "image/ief", (gpointer)image_ief);
g_hash_table_insert(mime_table, "image/jpeg", (gpointer)image_jpeg);
g_hash_table_insert(mime_table, "image/jutvision", (gpointer)image_jutvision);
g_hash_table_insert(mime_table, "image/naplps", (gpointer)image_naplps);
g_hash_table_insert(mime_table, "image/pict", (gpointer)image_pict);
g_hash_table_insert(mime_table, "image/png", (gpointer)image_png);
g_hash_table_insert(mime_table, "image/svg", (gpointer)image_svg);
g_hash_table_insert(mime_table, "image/svg+xml", (gpointer)image_svg_xml);
g_hash_table_insert(mime_table, "image/vnd.fpx", (gpointer)image_vnd_fpx);
g_hash_table_insert(mime_table, "image/vnd.microsoft.icon", (gpointer)image_vnd_microsoft_icon);
g_hash_table_insert(mime_table, "image/vnd.rn-realflash", (gpointer)image_vnd_rn_realflash);
g_hash_table_insert(mime_table, "image/vnd.rn-realpix", (gpointer)image_vnd_rn_realpix);
g_hash_table_insert(mime_table, "image/vnd.wap.wbmp", (gpointer)image_vnd_wap_wbmp);
g_hash_table_insert(mime_table, "image/vnd.xiff", (gpointer)image_vnd_xiff);
g_hash_table_insert(mime_table, "image/webp", (gpointer)image_webp);
g_hash_table_insert(mime_table, "image/x-cmu-raster", (gpointer)image_x_cmu_raster);
g_hash_table_insert(mime_table, "image/x-dwg", (gpointer)image_x_dwg);
g_hash_table_insert(mime_table, "image/x-eps", (gpointer)image_x_eps);
g_hash_table_insert(mime_table, "image/x-icns", (gpointer)image_x_icns);
g_hash_table_insert(mime_table, "image/x-icon", (gpointer)image_x_icon);
g_hash_table_insert(mime_table, "image/x-jg", (gpointer)image_x_jg);
g_hash_table_insert(mime_table, "image/x-jps", (gpointer)image_x_jps);
g_hash_table_insert(mime_table, "image/x-ms-bmp", (gpointer)image_x_ms_bmp);
g_hash_table_insert(mime_table, "image/x-niff", (gpointer)image_x_niff);
g_hash_table_insert(mime_table, "image/x-pcx", (gpointer)image_x_pcx);
g_hash_table_insert(mime_table, "image/x-pict", (gpointer)image_x_pict);
g_hash_table_insert(mime_table, "image/x-portable-bitmap", (gpointer)image_x_portable_bitmap);
g_hash_table_insert(mime_table, "image/x-portable-graymap", (gpointer)image_x_portable_graymap);
g_hash_table_insert(mime_table, "image/x-portable-pixmap", (gpointer)image_x_portable_pixmap);
g_hash_table_insert(mime_table, "image/x-quicktime", (gpointer)image_x_quicktime);
g_hash_table_insert(mime_table, "image/x-rgb", (gpointer)image_x_rgb);
g_hash_table_insert(mime_table, "image/x-tiff", (gpointer)image_x_tiff);
g_hash_table_insert(mime_table, "image/tiff", (gpointer)image_tiff);
g_hash_table_insert(mime_table, "image/x-xcf", (gpointer)image_x_xcf);
g_hash_table_insert(mime_table, "image/x-xpixmap", (gpointer)image_x_xpixmap);
g_hash_table_insert(mime_table, "message/rfc822", (gpointer)message_rfc822);
g_hash_table_insert(mime_table, "model/vnd.dwf", (gpointer)model_vnd_dwf);
g_hash_table_insert(mime_table, "model/vrml", (gpointer)model_vrml);
g_hash_table_insert(mime_table, "model/x-pov", (gpointer)model_x_pov);
g_hash_table_insert(mime_table, "text/asp", (gpointer)text_asp);
g_hash_table_insert(mime_table, "text/css", (gpointer)text_css);
g_hash_table_insert(mime_table, "text/x-sass", (gpointer)text_x_sass);
g_hash_table_insert(mime_table, "text/x-scss", (gpointer)text_x_scss);
g_hash_table_insert(mime_table, "text/html", (gpointer)text_html);
g_hash_table_insert(mime_table, "text/javascript", (gpointer)text_javascript);
g_hash_table_insert(mime_table, "text/mcf", (gpointer)text_mcf);
g_hash_table_insert(mime_table, "text/pascal", (gpointer)text_pascal);
g_hash_table_insert(mime_table, "text/plain", (gpointer)text_plain);
g_hash_table_insert(mime_table, "text/richtext", (gpointer)text_richtext);
g_hash_table_insert(mime_table, "text/scriplet", (gpointer)text_scriplet);
g_hash_table_insert(mime_table, "text/x-awk", (gpointer)text_x_awk);
g_hash_table_insert(mime_table, "video/x-jng", (gpointer)video_x_jng);
g_hash_table_insert(mime_table, "video/x-mng", (gpointer)video_x_mng);
g_hash_table_insert(mime_table, "image/x-cur", (gpointer)image_x_cur);
g_hash_table_insert(mime_table, "image/x-xwindowdump", (gpointer)image_x_xwindowdump);
g_hash_table_insert(mime_table, "image/vnd.adobe.photoshop", (gpointer)image_vnd_adobe_photoshop);
g_hash_table_insert(mime_table, "text/tab-separated-values", (gpointer)text_tab_separated_values);
g_hash_table_insert(mime_table, "text/troff", (gpointer)text_troff);
g_hash_table_insert(mime_table, "text/uri-list", (gpointer)text_uri_list);
g_hash_table_insert(mime_table, "text/vnd.abc", (gpointer)text_vnd_abc);
g_hash_table_insert(mime_table, "text/vnd.fmi.flexstor", (gpointer)text_vnd_fmi_flexstor);
g_hash_table_insert(mime_table, "text/vnd.wap.wmlscript", (gpointer)text_vnd_wap_wmlscript);
g_hash_table_insert(mime_table, "text/vnd.wap.wml", (gpointer)text_vnd_wap_wml);
g_hash_table_insert(mime_table, "text/webviewhtml", (gpointer)text_webviewhtml);
g_hash_table_insert(mime_table, "text/x-Algol68", (gpointer)text_x_Algol68);
g_hash_table_insert(mime_table, "text/x-asm", (gpointer)text_x_asm);
g_hash_table_insert(mime_table, "text/x-audiosoft-intra", (gpointer)text_x_audiosoft_intra);
g_hash_table_insert(mime_table, "text/x-bcpl", (gpointer)text_x_bcpl);
g_hash_table_insert(mime_table, "text/x-c", (gpointer)text_x_c);
g_hash_table_insert(mime_table, "text/x-c++", (gpointer)text_x_c__);
g_hash_table_insert(mime_table, "text/x-component", (gpointer)text_x_component);
g_hash_table_insert(mime_table, "text/x-diff", (gpointer)text_x_diff);
g_hash_table_insert(mime_table, "text/x-fortran", (gpointer)text_x_fortran);
g_hash_table_insert(mime_table, "text/x-java", (gpointer)text_x_java);
g_hash_table_insert(mime_table, "text/x-la-asf", (gpointer)text_x_la_asf);
g_hash_table_insert(mime_table, "text/x-lisp", (gpointer)text_x_lisp);
g_hash_table_insert(mime_table, "text/x-m4", (gpointer)text_x_m4);
g_hash_table_insert(mime_table, "text/x-makefile", (gpointer)text_x_makefile);
g_hash_table_insert(mime_table, "text/xml", (gpointer)text_xml);
g_hash_table_insert(mime_table, "text/x-m", (gpointer)text_x_m);
g_hash_table_insert(mime_table, "text/x-msdos-batch", (gpointer)text_x_msdos_batch);
g_hash_table_insert(mime_table, "text/x-pascal", (gpointer)text_x_pascal);
g_hash_table_insert(mime_table, "text/x-perl", (gpointer)text_x_perl);
g_hash_table_insert(mime_table, "text/x-php", (gpointer)text_x_php);
g_hash_table_insert(mime_table, "text/x-python", (gpointer)text_x_python);
g_hash_table_insert(mime_table, "text/x-ruby", (gpointer)text_x_ruby);
g_hash_table_insert(mime_table, "text/x-server-parsed-html", (gpointer)text_x_server_parsed_html);
g_hash_table_insert(mime_table, "text/x-setext", (gpointer)text_x_setext);
g_hash_table_insert(mime_table, "text/x-sgml", (gpointer)text_x_sgml);
g_hash_table_insert(mime_table, "text/x-shellscript", (gpointer)text_x_shellscript);
g_hash_table_insert(mime_table, "text/x-speech", (gpointer)text_x_speech);
g_hash_table_insert(mime_table, "text/x-tex", (gpointer)text_x_tex);
g_hash_table_insert(mime_table, "text/x-uil", (gpointer)text_x_uil);
g_hash_table_insert(mime_table, "text/x-uuencode", (gpointer)text_x_uuencode);
g_hash_table_insert(mime_table, "text/x-vcalendar", (gpointer)text_x_vcalendar);
g_hash_table_insert(mime_table, "video/animaflex", (gpointer)video_animaflex);
g_hash_table_insert(mime_table, "video/avi", (gpointer)video_avi);
g_hash_table_insert(mime_table, "video/avs-video", (gpointer)video_avs_video);
g_hash_table_insert(mime_table, "video/mp4", (gpointer)video_mp4);
g_hash_table_insert(mime_table, "video/mpeg", (gpointer)video_mpeg);
g_hash_table_insert(mime_table, "video/quicktime", (gpointer)video_quicktime);
g_hash_table_insert(mime_table, "video/vdo", (gpointer)video_vdo);
g_hash_table_insert(mime_table, "video/vivo", (gpointer)video_vivo);
g_hash_table_insert(mime_table, "video/vnd.rn-realvideo", (gpointer)video_vnd_rn_realvideo);
g_hash_table_insert(mime_table, "video/vosaic", (gpointer)video_vosaic);
g_hash_table_insert(mime_table, "video/webm", (gpointer)video_webm);
g_hash_table_insert(mime_table, "video/x-amt-demorun", (gpointer)video_x_amt_demorun);
g_hash_table_insert(mime_table, "video/x-amt-showrun", (gpointer)video_x_amt_showrun);
g_hash_table_insert(mime_table, "video/x-atomic3d-feature", (gpointer)video_x_atomic3d_feature);
g_hash_table_insert(mime_table, "video/x-dl", (gpointer)video_x_dl);
g_hash_table_insert(mime_table, "video/x-dv", (gpointer)video_x_dv);
g_hash_table_insert(mime_table, "video/x-fli", (gpointer)video_x_fli);
g_hash_table_insert(mime_table, "video/x-isvideo", (gpointer)video_x_isvideo);
g_hash_table_insert(mime_table, "video/x-motion-jpeg", (gpointer)video_x_motion_jpeg);
g_hash_table_insert(mime_table, "video/x-ms-asf", (gpointer)video_x_ms_asf);
g_hash_table_insert(mime_table, "video/x-qtc", (gpointer)video_x_qtc);
g_hash_table_insert(mime_table, "video/x-sgi-movie", (gpointer)video_x_sgi_movie);
g_hash_table_insert(mime_table, "application/x-7z-compressed", (gpointer)application_x_7z_compressed);
g_hash_table_insert(mime_table, "application/vnd.openxmlformats-officedocument.wordprocessingml.document", (gpointer)application_vnd_openxmlformats_officedocument_wordprocessingml_document);
g_hash_table_insert(mime_table, "text/x-po", (gpointer)text_x_po);
g_hash_table_insert(mime_table, "application/x-rpm", (gpointer)application_x_rpm);
g_hash_table_insert(mime_table, "application/x-debian-package", (gpointer)application_x_debian_package);
g_hash_table_insert(mime_table, "application/vnd.iccprofile", (gpointer)application_vnd_iccprofile);
g_hash_table_insert(mime_table, "application/dicom", (gpointer)application_dicom);
g_hash_table_insert(mime_table, "image/x-exr", (gpointer)image_x_exr);
g_hash_table_insert(mime_table, "video/x-matroska", (gpointer)video_x_matroska);
g_hash_table_insert(mime_table, "application/x-empty", (gpointer)application_x_empty);
g_hash_table_insert(mime_table, "model/vnd.gdl", (gpointer)model_vnd_gdl);
g_hash_table_insert(mime_table, "model/vnd.gs.gdl", (gpointer)model_vnd_gs_gdl);
g_hash_table_insert(mime_table, "font/woff", (gpointer)font_woff);
g_hash_table_insert(mime_table, "font/woff2", (gpointer)font_woff2);
g_hash_table_insert(mime_table, "application/epub+zip", (gpointer)application_epub_zip);
g_hash_table_insert(mime_table, "application/x-mobipocket-ebook", (gpointer)application_x_mobipocket_ebook);
g_hash_table_insert(mime_table, "audio/x-flac", (gpointer)audio_x_flac);
g_hash_table_insert(mime_table, "application/x-rar", (gpointer)application_x_rar);
g_hash_table_insert(mime_table, "video/x-msvideo", (gpointer)video_x_msvideo);
g_hash_table_insert(mime_table, "video/x-flv", (gpointer)video_x_flv);
g_hash_table_insert(mime_table, "application/x-kdelnk", (gpointer)application_x_kdelnk);
g_hash_table_insert(mime_table, "text/x-tcl", (gpointer)text_x_tcl);
g_hash_table_insert(mime_table, "application/ogg", (gpointer)application_ogg);
g_hash_table_insert(mime_table, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", (gpointer)application_vnd_openxmlformats_officedocument_spreadsheetml_sheet);
g_hash_table_insert(mime_table, "application/vnd.ms-cab-compressed", (gpointer)application_vnd_ms_cab_compressed);
g_hash_table_insert(mime_table, "audio/mp4", (gpointer)audio_mp4);
g_hash_table_insert(mime_table, "image/vnd.djvu", (gpointer)image_vnd_djvu);
g_hash_table_insert(mime_table, "application/x-ms-reader", (gpointer)application_x_ms_reader);
g_hash_table_insert(mime_table, "application/CDFV2-corrupt", (gpointer)application_CDFV2_corrupt);
g_hash_table_insert(mime_table, "text/x-vcard", (gpointer)text_x_vcard);
g_hash_table_insert(mime_table, "application/x-innosetup", (gpointer)application_x_innosetup);
g_hash_table_insert(mime_table, "application/winhelp", (gpointer)application_winhelp);
g_hash_table_insert(mime_table, "image/x-tga", (gpointer)image_x_tga);
g_hash_table_insert(mime_table, "application/x-wine-extension-ini", (gpointer)application_x_wine_extension_ini);
g_hash_table_insert(mime_table, "application/x-cbz", (gpointer)application_x_cbz);
g_hash_table_insert(mime_table, "application/x-cbr", (gpointer)application_x_cbr);
return mime_table;}
#endif
