install:
	install sist2-update-all.sh /usr/bin/sist2-update-all.sh
	install sist2-update-files.sh /usr/bin/sist2-update-files.sh
	install sist2-update-nextcloud.sh /usr/bin/sist2-update-nextcloud.sh
	install sist2-update.service /etc/systemd/system/sist2-update.service
	install sist2-update.timer /etc/systemd/system/sist2-update.timer
	systemctl daemon-reload
